// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/mail.proto

package com.kodgames.message.proto.mail;

public final class MailProtoBuf {
  private MailProtoBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MailProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 id = 1;
    /**
     * <code>required int64 id = 1;</code>
     *
     * <pre>
     * 邮件ID
     * </pre>
     */
    boolean hasId();
    /**
     * <code>required int64 id = 1;</code>
     *
     * <pre>
     * 邮件ID
     * </pre>
     */
    long getId();

    // required string msg = 2;
    /**
     * <code>required string msg = 2;</code>
     *
     * <pre>
     * 邮件内容
     * </pre>
     */
    boolean hasMsg();
    /**
     * <code>required string msg = 2;</code>
     *
     * <pre>
     * 邮件内容
     * </pre>
     */
    java.lang.String getMsg();
    /**
     * <code>required string msg = 2;</code>
     *
     * <pre>
     * 邮件内容
     * </pre>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    // required int32 type = 3;
    /**
     * <code>required int32 type = 3;</code>
     *
     * <pre>
     * 类型  2:绝对时间一次发送  3:按设定重复发送
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required int32 type = 3;</code>
     *
     * <pre>
     * 类型  2:绝对时间一次发送  3:按设定重复发送
     * </pre>
     */
    int getType();

    // required int64 time = 4;
    /**
     * <code>required int64 time = 4;</code>
     *
     * <pre>
     * 创建时间
     * </pre>
     */
    boolean hasTime();
    /**
     * <code>required int64 time = 4;</code>
     *
     * <pre>
     * 创建时间
     * </pre>
     */
    long getTime();
  }
  /**
   * Protobuf type {@code com.kodgames.message.proto.mail.MailProto}
   */
  public static final class MailProto extends
      com.google.protobuf.GeneratedMessage
      implements MailProtoOrBuilder {
    // Use MailProto.newBuilder() to construct.
    private MailProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MailProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MailProto defaultInstance;
    public static MailProto getDefaultInstance() {
      return defaultInstance;
    }

    public MailProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MailProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              msg_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              type_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              time_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kodgames.message.proto.mail.MailProtoBuf.internal_static_com_kodgames_message_proto_mail_MailProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kodgames.message.proto.mail.MailProtoBuf.internal_static_com_kodgames_message_proto_mail_MailProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kodgames.message.proto.mail.MailProtoBuf.MailProto.class, com.kodgames.message.proto.mail.MailProtoBuf.MailProto.Builder.class);
    }

    public static com.google.protobuf.Parser<MailProto> PARSER =
        new com.google.protobuf.AbstractParser<MailProto>() {
      public MailProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MailProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MailProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required int64 id = 1;</code>
     *
     * <pre>
     * 邮件ID
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 id = 1;</code>
     *
     * <pre>
     * 邮件ID
     * </pre>
     */
    public long getId() {
      return id_;
    }

    // required string msg = 2;
    public static final int MSG_FIELD_NUMBER = 2;
    private java.lang.Object msg_;
    /**
     * <code>required string msg = 2;</code>
     *
     * <pre>
     * 邮件内容
     * </pre>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string msg = 2;</code>
     *
     * <pre>
     * 邮件内容
     * </pre>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string msg = 2;</code>
     *
     * <pre>
     * 邮件内容
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 type = 3;
    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>required int32 type = 3;</code>
     *
     * <pre>
     * 类型  2:绝对时间一次发送  3:按设定重复发送
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 type = 3;</code>
     *
     * <pre>
     * 类型  2:绝对时间一次发送  3:按设定重复发送
     * </pre>
     */
    public int getType() {
      return type_;
    }

    // required int64 time = 4;
    public static final int TIME_FIELD_NUMBER = 4;
    private long time_;
    /**
     * <code>required int64 time = 4;</code>
     *
     * <pre>
     * 创建时间
     * </pre>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int64 time = 4;</code>
     *
     * <pre>
     * 创建时间
     * </pre>
     */
    public long getTime() {
      return time_;
    }

    private void initFields() {
      id_ = 0L;
      msg_ = "";
      type_ = 0;
      time_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMsgBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, type_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, time_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMsgBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, type_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, time_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.kodgames.message.proto.mail.MailProtoBuf.MailProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.MailProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.MailProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.MailProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.MailProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.MailProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.MailProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.MailProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.MailProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.MailProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.kodgames.message.proto.mail.MailProtoBuf.MailProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.kodgames.message.proto.mail.MailProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.kodgames.message.proto.mail.MailProtoBuf.MailProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kodgames.message.proto.mail.MailProtoBuf.internal_static_com_kodgames_message_proto_mail_MailProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kodgames.message.proto.mail.MailProtoBuf.internal_static_com_kodgames_message_proto_mail_MailProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kodgames.message.proto.mail.MailProtoBuf.MailProto.class, com.kodgames.message.proto.mail.MailProtoBuf.MailProto.Builder.class);
      }

      // Construct using com.kodgames.message.proto.mail.MailProtoBuf.MailProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        time_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kodgames.message.proto.mail.MailProtoBuf.internal_static_com_kodgames_message_proto_mail_MailProto_descriptor;
      }

      public com.kodgames.message.proto.mail.MailProtoBuf.MailProto getDefaultInstanceForType() {
        return com.kodgames.message.proto.mail.MailProtoBuf.MailProto.getDefaultInstance();
      }

      public com.kodgames.message.proto.mail.MailProtoBuf.MailProto build() {
        com.kodgames.message.proto.mail.MailProtoBuf.MailProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kodgames.message.proto.mail.MailProtoBuf.MailProto buildPartial() {
        com.kodgames.message.proto.mail.MailProtoBuf.MailProto result = new com.kodgames.message.proto.mail.MailProtoBuf.MailProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msg_ = msg_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.time_ = time_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kodgames.message.proto.mail.MailProtoBuf.MailProto) {
          return mergeFrom((com.kodgames.message.proto.mail.MailProtoBuf.MailProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kodgames.message.proto.mail.MailProtoBuf.MailProto other) {
        if (other == com.kodgames.message.proto.mail.MailProtoBuf.MailProto.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasMsg()) {
          bitField0_ |= 0x00000002;
          msg_ = other.msg_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasMsg()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!hasTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kodgames.message.proto.mail.MailProtoBuf.MailProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kodgames.message.proto.mail.MailProtoBuf.MailProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 id = 1;
      private long id_ ;
      /**
       * <code>required int64 id = 1;</code>
       *
       * <pre>
       * 邮件ID
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 id = 1;</code>
       *
       * <pre>
       * 邮件ID
       * </pre>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required int64 id = 1;</code>
       *
       * <pre>
       * 邮件ID
       * </pre>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 id = 1;</code>
       *
       * <pre>
       * 邮件ID
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      // required string msg = 2;
      private java.lang.Object msg_ = "";
      /**
       * <code>required string msg = 2;</code>
       *
       * <pre>
       * 邮件内容
       * </pre>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string msg = 2;</code>
       *
       * <pre>
       * 邮件内容
       * </pre>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string msg = 2;</code>
       *
       * <pre>
       * 邮件内容
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string msg = 2;</code>
       *
       * <pre>
       * 邮件内容
       * </pre>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string msg = 2;</code>
       *
       * <pre>
       * 邮件内容
       * </pre>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>required string msg = 2;</code>
       *
       * <pre>
       * 邮件内容
       * </pre>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msg_ = value;
        onChanged();
        return this;
      }

      // required int32 type = 3;
      private int type_ ;
      /**
       * <code>required int32 type = 3;</code>
       *
       * <pre>
       * 类型  2:绝对时间一次发送  3:按设定重复发送
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 type = 3;</code>
       *
       * <pre>
       * 类型  2:绝对时间一次发送  3:按设定重复发送
       * </pre>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 type = 3;</code>
       *
       * <pre>
       * 类型  2:绝对时间一次发送  3:按设定重复发送
       * </pre>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 type = 3;</code>
       *
       * <pre>
       * 类型  2:绝对时间一次发送  3:按设定重复发送
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 0;
        onChanged();
        return this;
      }

      // required int64 time = 4;
      private long time_ ;
      /**
       * <code>required int64 time = 4;</code>
       *
       * <pre>
       * 创建时间
       * </pre>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 time = 4;</code>
       *
       * <pre>
       * 创建时间
       * </pre>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>required int64 time = 4;</code>
       *
       * <pre>
       * 创建时间
       * </pre>
       */
      public Builder setTime(long value) {
        bitField0_ |= 0x00000008;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 time = 4;</code>
       *
       * <pre>
       * 创建时间
       * </pre>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        time_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.kodgames.message.proto.mail.MailProto)
    }

    static {
      defaultInstance = new MailProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.kodgames.message.proto.mail.MailProto)
  }

  public interface GCNewMailSYNCOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.kodgames.message.proto.mail.GCNewMailSYNC}
   */
  public static final class GCNewMailSYNC extends
      com.google.protobuf.GeneratedMessage
      implements GCNewMailSYNCOrBuilder {
    // Use GCNewMailSYNC.newBuilder() to construct.
    private GCNewMailSYNC(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GCNewMailSYNC(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GCNewMailSYNC defaultInstance;
    public static GCNewMailSYNC getDefaultInstance() {
      return defaultInstance;
    }

    public GCNewMailSYNC getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GCNewMailSYNC(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kodgames.message.proto.mail.MailProtoBuf.internal_static_com_kodgames_message_proto_mail_GCNewMailSYNC_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kodgames.message.proto.mail.MailProtoBuf.internal_static_com_kodgames_message_proto_mail_GCNewMailSYNC_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kodgames.message.proto.mail.MailProtoBuf.GCNewMailSYNC.class, com.kodgames.message.proto.mail.MailProtoBuf.GCNewMailSYNC.Builder.class);
    }

    public static com.google.protobuf.Parser<GCNewMailSYNC> PARSER =
        new com.google.protobuf.AbstractParser<GCNewMailSYNC>() {
      public GCNewMailSYNC parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GCNewMailSYNC(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GCNewMailSYNC> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.kodgames.message.proto.mail.MailProtoBuf.GCNewMailSYNC parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.GCNewMailSYNC parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.GCNewMailSYNC parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.GCNewMailSYNC parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.GCNewMailSYNC parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.GCNewMailSYNC parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.GCNewMailSYNC parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.GCNewMailSYNC parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.GCNewMailSYNC parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.GCNewMailSYNC parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.kodgames.message.proto.mail.MailProtoBuf.GCNewMailSYNC prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.kodgames.message.proto.mail.GCNewMailSYNC}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.kodgames.message.proto.mail.MailProtoBuf.GCNewMailSYNCOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kodgames.message.proto.mail.MailProtoBuf.internal_static_com_kodgames_message_proto_mail_GCNewMailSYNC_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kodgames.message.proto.mail.MailProtoBuf.internal_static_com_kodgames_message_proto_mail_GCNewMailSYNC_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kodgames.message.proto.mail.MailProtoBuf.GCNewMailSYNC.class, com.kodgames.message.proto.mail.MailProtoBuf.GCNewMailSYNC.Builder.class);
      }

      // Construct using com.kodgames.message.proto.mail.MailProtoBuf.GCNewMailSYNC.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kodgames.message.proto.mail.MailProtoBuf.internal_static_com_kodgames_message_proto_mail_GCNewMailSYNC_descriptor;
      }

      public com.kodgames.message.proto.mail.MailProtoBuf.GCNewMailSYNC getDefaultInstanceForType() {
        return com.kodgames.message.proto.mail.MailProtoBuf.GCNewMailSYNC.getDefaultInstance();
      }

      public com.kodgames.message.proto.mail.MailProtoBuf.GCNewMailSYNC build() {
        com.kodgames.message.proto.mail.MailProtoBuf.GCNewMailSYNC result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kodgames.message.proto.mail.MailProtoBuf.GCNewMailSYNC buildPartial() {
        com.kodgames.message.proto.mail.MailProtoBuf.GCNewMailSYNC result = new com.kodgames.message.proto.mail.MailProtoBuf.GCNewMailSYNC(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kodgames.message.proto.mail.MailProtoBuf.GCNewMailSYNC) {
          return mergeFrom((com.kodgames.message.proto.mail.MailProtoBuf.GCNewMailSYNC)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kodgames.message.proto.mail.MailProtoBuf.GCNewMailSYNC other) {
        if (other == com.kodgames.message.proto.mail.MailProtoBuf.GCNewMailSYNC.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kodgames.message.proto.mail.MailProtoBuf.GCNewMailSYNC parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kodgames.message.proto.mail.MailProtoBuf.GCNewMailSYNC) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.kodgames.message.proto.mail.GCNewMailSYNC)
    }

    static {
      defaultInstance = new GCNewMailSYNC(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.kodgames.message.proto.mail.GCNewMailSYNC)
  }

  public interface CGMailREQOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 time = 1;
    /**
     * <code>optional int64 time = 1;</code>
     *
     * <pre>
     * 客户端最后的缓存时间
     * </pre>
     */
    boolean hasTime();
    /**
     * <code>optional int64 time = 1;</code>
     *
     * <pre>
     * 客户端最后的缓存时间
     * </pre>
     */
    long getTime();
  }
  /**
   * Protobuf type {@code com.kodgames.message.proto.mail.CGMailREQ}
   */
  public static final class CGMailREQ extends
      com.google.protobuf.GeneratedMessage
      implements CGMailREQOrBuilder {
    // Use CGMailREQ.newBuilder() to construct.
    private CGMailREQ(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CGMailREQ(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CGMailREQ defaultInstance;
    public static CGMailREQ getDefaultInstance() {
      return defaultInstance;
    }

    public CGMailREQ getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CGMailREQ(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              time_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kodgames.message.proto.mail.MailProtoBuf.internal_static_com_kodgames_message_proto_mail_CGMailREQ_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kodgames.message.proto.mail.MailProtoBuf.internal_static_com_kodgames_message_proto_mail_CGMailREQ_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kodgames.message.proto.mail.MailProtoBuf.CGMailREQ.class, com.kodgames.message.proto.mail.MailProtoBuf.CGMailREQ.Builder.class);
    }

    public static com.google.protobuf.Parser<CGMailREQ> PARSER =
        new com.google.protobuf.AbstractParser<CGMailREQ>() {
      public CGMailREQ parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CGMailREQ(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CGMailREQ> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 time = 1;
    public static final int TIME_FIELD_NUMBER = 1;
    private long time_;
    /**
     * <code>optional int64 time = 1;</code>
     *
     * <pre>
     * 客户端最后的缓存时间
     * </pre>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 time = 1;</code>
     *
     * <pre>
     * 客户端最后的缓存时间
     * </pre>
     */
    public long getTime() {
      return time_;
    }

    private void initFields() {
      time_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, time_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, time_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.kodgames.message.proto.mail.MailProtoBuf.CGMailREQ parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.CGMailREQ parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.CGMailREQ parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.CGMailREQ parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.CGMailREQ parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.CGMailREQ parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.CGMailREQ parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.CGMailREQ parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.CGMailREQ parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.CGMailREQ parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.kodgames.message.proto.mail.MailProtoBuf.CGMailREQ prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.kodgames.message.proto.mail.CGMailREQ}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.kodgames.message.proto.mail.MailProtoBuf.CGMailREQOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kodgames.message.proto.mail.MailProtoBuf.internal_static_com_kodgames_message_proto_mail_CGMailREQ_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kodgames.message.proto.mail.MailProtoBuf.internal_static_com_kodgames_message_proto_mail_CGMailREQ_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kodgames.message.proto.mail.MailProtoBuf.CGMailREQ.class, com.kodgames.message.proto.mail.MailProtoBuf.CGMailREQ.Builder.class);
      }

      // Construct using com.kodgames.message.proto.mail.MailProtoBuf.CGMailREQ.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        time_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kodgames.message.proto.mail.MailProtoBuf.internal_static_com_kodgames_message_proto_mail_CGMailREQ_descriptor;
      }

      public com.kodgames.message.proto.mail.MailProtoBuf.CGMailREQ getDefaultInstanceForType() {
        return com.kodgames.message.proto.mail.MailProtoBuf.CGMailREQ.getDefaultInstance();
      }

      public com.kodgames.message.proto.mail.MailProtoBuf.CGMailREQ build() {
        com.kodgames.message.proto.mail.MailProtoBuf.CGMailREQ result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kodgames.message.proto.mail.MailProtoBuf.CGMailREQ buildPartial() {
        com.kodgames.message.proto.mail.MailProtoBuf.CGMailREQ result = new com.kodgames.message.proto.mail.MailProtoBuf.CGMailREQ(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.time_ = time_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kodgames.message.proto.mail.MailProtoBuf.CGMailREQ) {
          return mergeFrom((com.kodgames.message.proto.mail.MailProtoBuf.CGMailREQ)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kodgames.message.proto.mail.MailProtoBuf.CGMailREQ other) {
        if (other == com.kodgames.message.proto.mail.MailProtoBuf.CGMailREQ.getDefaultInstance()) return this;
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kodgames.message.proto.mail.MailProtoBuf.CGMailREQ parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kodgames.message.proto.mail.MailProtoBuf.CGMailREQ) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 time = 1;
      private long time_ ;
      /**
       * <code>optional int64 time = 1;</code>
       *
       * <pre>
       * 客户端最后的缓存时间
       * </pre>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 time = 1;</code>
       *
       * <pre>
       * 客户端最后的缓存时间
       * </pre>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>optional int64 time = 1;</code>
       *
       * <pre>
       * 客户端最后的缓存时间
       * </pre>
       */
      public Builder setTime(long value) {
        bitField0_ |= 0x00000001;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 time = 1;</code>
       *
       * <pre>
       * 客户端最后的缓存时间
       * </pre>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.kodgames.message.proto.mail.CGMailREQ)
    }

    static {
      defaultInstance = new CGMailREQ(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.kodgames.message.proto.mail.CGMailREQ)
  }

  public interface GCMailRESOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 lastCheckTime = 1;
    /**
     * <code>required int64 lastCheckTime = 1;</code>
     *
     * <pre>
     * 最新检查时间
     * </pre>
     */
    boolean hasLastCheckTime();
    /**
     * <code>required int64 lastCheckTime = 1;</code>
     *
     * <pre>
     * 最新检查时间
     * </pre>
     */
    long getLastCheckTime();

    // required int64 oldCheckTime = 2;
    /**
     * <code>required int64 oldCheckTime = 2;</code>
     *
     * <pre>
     * 旧邮件检查时间
     * </pre>
     */
    boolean hasOldCheckTime();
    /**
     * <code>required int64 oldCheckTime = 2;</code>
     *
     * <pre>
     * 旧邮件检查时间
     * </pre>
     */
    long getOldCheckTime();

    // repeated .com.kodgames.message.proto.mail.MailProto mails = 3;
    /**
     * <code>repeated .com.kodgames.message.proto.mail.MailProto mails = 3;</code>
     *
     * <pre>
     * 邮件列表
     * </pre>
     */
    java.util.List<com.kodgames.message.proto.mail.MailProtoBuf.MailProto> 
        getMailsList();
    /**
     * <code>repeated .com.kodgames.message.proto.mail.MailProto mails = 3;</code>
     *
     * <pre>
     * 邮件列表
     * </pre>
     */
    com.kodgames.message.proto.mail.MailProtoBuf.MailProto getMails(int index);
    /**
     * <code>repeated .com.kodgames.message.proto.mail.MailProto mails = 3;</code>
     *
     * <pre>
     * 邮件列表
     * </pre>
     */
    int getMailsCount();
    /**
     * <code>repeated .com.kodgames.message.proto.mail.MailProto mails = 3;</code>
     *
     * <pre>
     * 邮件列表
     * </pre>
     */
    java.util.List<? extends com.kodgames.message.proto.mail.MailProtoBuf.MailProtoOrBuilder> 
        getMailsOrBuilderList();
    /**
     * <code>repeated .com.kodgames.message.proto.mail.MailProto mails = 3;</code>
     *
     * <pre>
     * 邮件列表
     * </pre>
     */
    com.kodgames.message.proto.mail.MailProtoBuf.MailProtoOrBuilder getMailsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.kodgames.message.proto.mail.GCMailRES}
   */
  public static final class GCMailRES extends
      com.google.protobuf.GeneratedMessage
      implements GCMailRESOrBuilder {
    // Use GCMailRES.newBuilder() to construct.
    private GCMailRES(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GCMailRES(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GCMailRES defaultInstance;
    public static GCMailRES getDefaultInstance() {
      return defaultInstance;
    }

    public GCMailRES getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GCMailRES(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              lastCheckTime_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              oldCheckTime_ = input.readInt64();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                mails_ = new java.util.ArrayList<com.kodgames.message.proto.mail.MailProtoBuf.MailProto>();
                mutable_bitField0_ |= 0x00000004;
              }
              mails_.add(input.readMessage(com.kodgames.message.proto.mail.MailProtoBuf.MailProto.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          mails_ = java.util.Collections.unmodifiableList(mails_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kodgames.message.proto.mail.MailProtoBuf.internal_static_com_kodgames_message_proto_mail_GCMailRES_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kodgames.message.proto.mail.MailProtoBuf.internal_static_com_kodgames_message_proto_mail_GCMailRES_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kodgames.message.proto.mail.MailProtoBuf.GCMailRES.class, com.kodgames.message.proto.mail.MailProtoBuf.GCMailRES.Builder.class);
    }

    public static com.google.protobuf.Parser<GCMailRES> PARSER =
        new com.google.protobuf.AbstractParser<GCMailRES>() {
      public GCMailRES parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GCMailRES(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GCMailRES> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 lastCheckTime = 1;
    public static final int LASTCHECKTIME_FIELD_NUMBER = 1;
    private long lastCheckTime_;
    /**
     * <code>required int64 lastCheckTime = 1;</code>
     *
     * <pre>
     * 最新检查时间
     * </pre>
     */
    public boolean hasLastCheckTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 lastCheckTime = 1;</code>
     *
     * <pre>
     * 最新检查时间
     * </pre>
     */
    public long getLastCheckTime() {
      return lastCheckTime_;
    }

    // required int64 oldCheckTime = 2;
    public static final int OLDCHECKTIME_FIELD_NUMBER = 2;
    private long oldCheckTime_;
    /**
     * <code>required int64 oldCheckTime = 2;</code>
     *
     * <pre>
     * 旧邮件检查时间
     * </pre>
     */
    public boolean hasOldCheckTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 oldCheckTime = 2;</code>
     *
     * <pre>
     * 旧邮件检查时间
     * </pre>
     */
    public long getOldCheckTime() {
      return oldCheckTime_;
    }

    // repeated .com.kodgames.message.proto.mail.MailProto mails = 3;
    public static final int MAILS_FIELD_NUMBER = 3;
    private java.util.List<com.kodgames.message.proto.mail.MailProtoBuf.MailProto> mails_;
    /**
     * <code>repeated .com.kodgames.message.proto.mail.MailProto mails = 3;</code>
     *
     * <pre>
     * 邮件列表
     * </pre>
     */
    public java.util.List<com.kodgames.message.proto.mail.MailProtoBuf.MailProto> getMailsList() {
      return mails_;
    }
    /**
     * <code>repeated .com.kodgames.message.proto.mail.MailProto mails = 3;</code>
     *
     * <pre>
     * 邮件列表
     * </pre>
     */
    public java.util.List<? extends com.kodgames.message.proto.mail.MailProtoBuf.MailProtoOrBuilder> 
        getMailsOrBuilderList() {
      return mails_;
    }
    /**
     * <code>repeated .com.kodgames.message.proto.mail.MailProto mails = 3;</code>
     *
     * <pre>
     * 邮件列表
     * </pre>
     */
    public int getMailsCount() {
      return mails_.size();
    }
    /**
     * <code>repeated .com.kodgames.message.proto.mail.MailProto mails = 3;</code>
     *
     * <pre>
     * 邮件列表
     * </pre>
     */
    public com.kodgames.message.proto.mail.MailProtoBuf.MailProto getMails(int index) {
      return mails_.get(index);
    }
    /**
     * <code>repeated .com.kodgames.message.proto.mail.MailProto mails = 3;</code>
     *
     * <pre>
     * 邮件列表
     * </pre>
     */
    public com.kodgames.message.proto.mail.MailProtoBuf.MailProtoOrBuilder getMailsOrBuilder(
        int index) {
      return mails_.get(index);
    }

    private void initFields() {
      lastCheckTime_ = 0L;
      oldCheckTime_ = 0L;
      mails_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasLastCheckTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOldCheckTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getMailsCount(); i++) {
        if (!getMails(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, lastCheckTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, oldCheckTime_);
      }
      for (int i = 0; i < mails_.size(); i++) {
        output.writeMessage(3, mails_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, lastCheckTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, oldCheckTime_);
      }
      for (int i = 0; i < mails_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, mails_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.kodgames.message.proto.mail.MailProtoBuf.GCMailRES parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.GCMailRES parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.GCMailRES parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.GCMailRES parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.GCMailRES parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.GCMailRES parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.GCMailRES parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.GCMailRES parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.GCMailRES parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kodgames.message.proto.mail.MailProtoBuf.GCMailRES parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.kodgames.message.proto.mail.MailProtoBuf.GCMailRES prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.kodgames.message.proto.mail.GCMailRES}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.kodgames.message.proto.mail.MailProtoBuf.GCMailRESOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kodgames.message.proto.mail.MailProtoBuf.internal_static_com_kodgames_message_proto_mail_GCMailRES_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kodgames.message.proto.mail.MailProtoBuf.internal_static_com_kodgames_message_proto_mail_GCMailRES_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kodgames.message.proto.mail.MailProtoBuf.GCMailRES.class, com.kodgames.message.proto.mail.MailProtoBuf.GCMailRES.Builder.class);
      }

      // Construct using com.kodgames.message.proto.mail.MailProtoBuf.GCMailRES.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMailsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        lastCheckTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        oldCheckTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (mailsBuilder_ == null) {
          mails_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          mailsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kodgames.message.proto.mail.MailProtoBuf.internal_static_com_kodgames_message_proto_mail_GCMailRES_descriptor;
      }

      public com.kodgames.message.proto.mail.MailProtoBuf.GCMailRES getDefaultInstanceForType() {
        return com.kodgames.message.proto.mail.MailProtoBuf.GCMailRES.getDefaultInstance();
      }

      public com.kodgames.message.proto.mail.MailProtoBuf.GCMailRES build() {
        com.kodgames.message.proto.mail.MailProtoBuf.GCMailRES result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kodgames.message.proto.mail.MailProtoBuf.GCMailRES buildPartial() {
        com.kodgames.message.proto.mail.MailProtoBuf.GCMailRES result = new com.kodgames.message.proto.mail.MailProtoBuf.GCMailRES(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.lastCheckTime_ = lastCheckTime_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.oldCheckTime_ = oldCheckTime_;
        if (mailsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            mails_ = java.util.Collections.unmodifiableList(mails_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.mails_ = mails_;
        } else {
          result.mails_ = mailsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kodgames.message.proto.mail.MailProtoBuf.GCMailRES) {
          return mergeFrom((com.kodgames.message.proto.mail.MailProtoBuf.GCMailRES)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kodgames.message.proto.mail.MailProtoBuf.GCMailRES other) {
        if (other == com.kodgames.message.proto.mail.MailProtoBuf.GCMailRES.getDefaultInstance()) return this;
        if (other.hasLastCheckTime()) {
          setLastCheckTime(other.getLastCheckTime());
        }
        if (other.hasOldCheckTime()) {
          setOldCheckTime(other.getOldCheckTime());
        }
        if (mailsBuilder_ == null) {
          if (!other.mails_.isEmpty()) {
            if (mails_.isEmpty()) {
              mails_ = other.mails_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureMailsIsMutable();
              mails_.addAll(other.mails_);
            }
            onChanged();
          }
        } else {
          if (!other.mails_.isEmpty()) {
            if (mailsBuilder_.isEmpty()) {
              mailsBuilder_.dispose();
              mailsBuilder_ = null;
              mails_ = other.mails_;
              bitField0_ = (bitField0_ & ~0x00000004);
              mailsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMailsFieldBuilder() : null;
            } else {
              mailsBuilder_.addAllMessages(other.mails_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLastCheckTime()) {
          
          return false;
        }
        if (!hasOldCheckTime()) {
          
          return false;
        }
        for (int i = 0; i < getMailsCount(); i++) {
          if (!getMails(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kodgames.message.proto.mail.MailProtoBuf.GCMailRES parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kodgames.message.proto.mail.MailProtoBuf.GCMailRES) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 lastCheckTime = 1;
      private long lastCheckTime_ ;
      /**
       * <code>required int64 lastCheckTime = 1;</code>
       *
       * <pre>
       * 最新检查时间
       * </pre>
       */
      public boolean hasLastCheckTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 lastCheckTime = 1;</code>
       *
       * <pre>
       * 最新检查时间
       * </pre>
       */
      public long getLastCheckTime() {
        return lastCheckTime_;
      }
      /**
       * <code>required int64 lastCheckTime = 1;</code>
       *
       * <pre>
       * 最新检查时间
       * </pre>
       */
      public Builder setLastCheckTime(long value) {
        bitField0_ |= 0x00000001;
        lastCheckTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 lastCheckTime = 1;</code>
       *
       * <pre>
       * 最新检查时间
       * </pre>
       */
      public Builder clearLastCheckTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        lastCheckTime_ = 0L;
        onChanged();
        return this;
      }

      // required int64 oldCheckTime = 2;
      private long oldCheckTime_ ;
      /**
       * <code>required int64 oldCheckTime = 2;</code>
       *
       * <pre>
       * 旧邮件检查时间
       * </pre>
       */
      public boolean hasOldCheckTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 oldCheckTime = 2;</code>
       *
       * <pre>
       * 旧邮件检查时间
       * </pre>
       */
      public long getOldCheckTime() {
        return oldCheckTime_;
      }
      /**
       * <code>required int64 oldCheckTime = 2;</code>
       *
       * <pre>
       * 旧邮件检查时间
       * </pre>
       */
      public Builder setOldCheckTime(long value) {
        bitField0_ |= 0x00000002;
        oldCheckTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 oldCheckTime = 2;</code>
       *
       * <pre>
       * 旧邮件检查时间
       * </pre>
       */
      public Builder clearOldCheckTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        oldCheckTime_ = 0L;
        onChanged();
        return this;
      }

      // repeated .com.kodgames.message.proto.mail.MailProto mails = 3;
      private java.util.List<com.kodgames.message.proto.mail.MailProtoBuf.MailProto> mails_ =
        java.util.Collections.emptyList();
      private void ensureMailsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          mails_ = new java.util.ArrayList<com.kodgames.message.proto.mail.MailProtoBuf.MailProto>(mails_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.kodgames.message.proto.mail.MailProtoBuf.MailProto, com.kodgames.message.proto.mail.MailProtoBuf.MailProto.Builder, com.kodgames.message.proto.mail.MailProtoBuf.MailProtoOrBuilder> mailsBuilder_;

      /**
       * <code>repeated .com.kodgames.message.proto.mail.MailProto mails = 3;</code>
       *
       * <pre>
       * 邮件列表
       * </pre>
       */
      public java.util.List<com.kodgames.message.proto.mail.MailProtoBuf.MailProto> getMailsList() {
        if (mailsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(mails_);
        } else {
          return mailsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.kodgames.message.proto.mail.MailProto mails = 3;</code>
       *
       * <pre>
       * 邮件列表
       * </pre>
       */
      public int getMailsCount() {
        if (mailsBuilder_ == null) {
          return mails_.size();
        } else {
          return mailsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.kodgames.message.proto.mail.MailProto mails = 3;</code>
       *
       * <pre>
       * 邮件列表
       * </pre>
       */
      public com.kodgames.message.proto.mail.MailProtoBuf.MailProto getMails(int index) {
        if (mailsBuilder_ == null) {
          return mails_.get(index);
        } else {
          return mailsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.kodgames.message.proto.mail.MailProto mails = 3;</code>
       *
       * <pre>
       * 邮件列表
       * </pre>
       */
      public Builder setMails(
          int index, com.kodgames.message.proto.mail.MailProtoBuf.MailProto value) {
        if (mailsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMailsIsMutable();
          mails_.set(index, value);
          onChanged();
        } else {
          mailsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.kodgames.message.proto.mail.MailProto mails = 3;</code>
       *
       * <pre>
       * 邮件列表
       * </pre>
       */
      public Builder setMails(
          int index, com.kodgames.message.proto.mail.MailProtoBuf.MailProto.Builder builderForValue) {
        if (mailsBuilder_ == null) {
          ensureMailsIsMutable();
          mails_.set(index, builderForValue.build());
          onChanged();
        } else {
          mailsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.kodgames.message.proto.mail.MailProto mails = 3;</code>
       *
       * <pre>
       * 邮件列表
       * </pre>
       */
      public Builder addMails(com.kodgames.message.proto.mail.MailProtoBuf.MailProto value) {
        if (mailsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMailsIsMutable();
          mails_.add(value);
          onChanged();
        } else {
          mailsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.kodgames.message.proto.mail.MailProto mails = 3;</code>
       *
       * <pre>
       * 邮件列表
       * </pre>
       */
      public Builder addMails(
          int index, com.kodgames.message.proto.mail.MailProtoBuf.MailProto value) {
        if (mailsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMailsIsMutable();
          mails_.add(index, value);
          onChanged();
        } else {
          mailsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.kodgames.message.proto.mail.MailProto mails = 3;</code>
       *
       * <pre>
       * 邮件列表
       * </pre>
       */
      public Builder addMails(
          com.kodgames.message.proto.mail.MailProtoBuf.MailProto.Builder builderForValue) {
        if (mailsBuilder_ == null) {
          ensureMailsIsMutable();
          mails_.add(builderForValue.build());
          onChanged();
        } else {
          mailsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.kodgames.message.proto.mail.MailProto mails = 3;</code>
       *
       * <pre>
       * 邮件列表
       * </pre>
       */
      public Builder addMails(
          int index, com.kodgames.message.proto.mail.MailProtoBuf.MailProto.Builder builderForValue) {
        if (mailsBuilder_ == null) {
          ensureMailsIsMutable();
          mails_.add(index, builderForValue.build());
          onChanged();
        } else {
          mailsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.kodgames.message.proto.mail.MailProto mails = 3;</code>
       *
       * <pre>
       * 邮件列表
       * </pre>
       */
      public Builder addAllMails(
          java.lang.Iterable<? extends com.kodgames.message.proto.mail.MailProtoBuf.MailProto> values) {
        if (mailsBuilder_ == null) {
          ensureMailsIsMutable();
          super.addAll(values, mails_);
          onChanged();
        } else {
          mailsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.kodgames.message.proto.mail.MailProto mails = 3;</code>
       *
       * <pre>
       * 邮件列表
       * </pre>
       */
      public Builder clearMails() {
        if (mailsBuilder_ == null) {
          mails_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          mailsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.kodgames.message.proto.mail.MailProto mails = 3;</code>
       *
       * <pre>
       * 邮件列表
       * </pre>
       */
      public Builder removeMails(int index) {
        if (mailsBuilder_ == null) {
          ensureMailsIsMutable();
          mails_.remove(index);
          onChanged();
        } else {
          mailsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.kodgames.message.proto.mail.MailProto mails = 3;</code>
       *
       * <pre>
       * 邮件列表
       * </pre>
       */
      public com.kodgames.message.proto.mail.MailProtoBuf.MailProto.Builder getMailsBuilder(
          int index) {
        return getMailsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.kodgames.message.proto.mail.MailProto mails = 3;</code>
       *
       * <pre>
       * 邮件列表
       * </pre>
       */
      public com.kodgames.message.proto.mail.MailProtoBuf.MailProtoOrBuilder getMailsOrBuilder(
          int index) {
        if (mailsBuilder_ == null) {
          return mails_.get(index);  } else {
          return mailsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.kodgames.message.proto.mail.MailProto mails = 3;</code>
       *
       * <pre>
       * 邮件列表
       * </pre>
       */
      public java.util.List<? extends com.kodgames.message.proto.mail.MailProtoBuf.MailProtoOrBuilder> 
           getMailsOrBuilderList() {
        if (mailsBuilder_ != null) {
          return mailsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(mails_);
        }
      }
      /**
       * <code>repeated .com.kodgames.message.proto.mail.MailProto mails = 3;</code>
       *
       * <pre>
       * 邮件列表
       * </pre>
       */
      public com.kodgames.message.proto.mail.MailProtoBuf.MailProto.Builder addMailsBuilder() {
        return getMailsFieldBuilder().addBuilder(
            com.kodgames.message.proto.mail.MailProtoBuf.MailProto.getDefaultInstance());
      }
      /**
       * <code>repeated .com.kodgames.message.proto.mail.MailProto mails = 3;</code>
       *
       * <pre>
       * 邮件列表
       * </pre>
       */
      public com.kodgames.message.proto.mail.MailProtoBuf.MailProto.Builder addMailsBuilder(
          int index) {
        return getMailsFieldBuilder().addBuilder(
            index, com.kodgames.message.proto.mail.MailProtoBuf.MailProto.getDefaultInstance());
      }
      /**
       * <code>repeated .com.kodgames.message.proto.mail.MailProto mails = 3;</code>
       *
       * <pre>
       * 邮件列表
       * </pre>
       */
      public java.util.List<com.kodgames.message.proto.mail.MailProtoBuf.MailProto.Builder> 
           getMailsBuilderList() {
        return getMailsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.kodgames.message.proto.mail.MailProtoBuf.MailProto, com.kodgames.message.proto.mail.MailProtoBuf.MailProto.Builder, com.kodgames.message.proto.mail.MailProtoBuf.MailProtoOrBuilder> 
          getMailsFieldBuilder() {
        if (mailsBuilder_ == null) {
          mailsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.kodgames.message.proto.mail.MailProtoBuf.MailProto, com.kodgames.message.proto.mail.MailProtoBuf.MailProto.Builder, com.kodgames.message.proto.mail.MailProtoBuf.MailProtoOrBuilder>(
                  mails_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          mails_ = null;
        }
        return mailsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.kodgames.message.proto.mail.GCMailRES)
    }

    static {
      defaultInstance = new GCMailRES(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.kodgames.message.proto.mail.GCMailRES)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kodgames_message_proto_mail_MailProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_kodgames_message_proto_mail_MailProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kodgames_message_proto_mail_GCNewMailSYNC_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_kodgames_message_proto_mail_GCNewMailSYNC_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kodgames_message_proto_mail_CGMailREQ_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_kodgames_message_proto_mail_CGMailREQ_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kodgames_message_proto_mail_GCMailRES_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_kodgames_message_proto_mail_GCMailRES_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023protobuf/mail.proto\022\037com.kodgames.mess" +
      "age.proto.mail\"@\n\tMailProto\022\n\n\002id\030\001 \002(\003\022" +
      "\013\n\003msg\030\002 \002(\t\022\014\n\004type\030\003 \002(\005\022\014\n\004time\030\004 \002(\003" +
      "\"\017\n\rGCNewMailSYNC\"\031\n\tCGMailREQ\022\014\n\004time\030\001" +
      " \001(\003\"s\n\tGCMailRES\022\025\n\rlastCheckTime\030\001 \002(\003" +
      "\022\024\n\014oldCheckTime\030\002 \002(\003\0229\n\005mails\030\003 \003(\0132*." +
      "com.kodgames.message.proto.mail.MailProt" +
      "oB\016B\014MailProtoBuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_kodgames_message_proto_mail_MailProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_kodgames_message_proto_mail_MailProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_kodgames_message_proto_mail_MailProto_descriptor,
              new java.lang.String[] { "Id", "Msg", "Type", "Time", });
          internal_static_com_kodgames_message_proto_mail_GCNewMailSYNC_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_kodgames_message_proto_mail_GCNewMailSYNC_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_kodgames_message_proto_mail_GCNewMailSYNC_descriptor,
              new java.lang.String[] { });
          internal_static_com_kodgames_message_proto_mail_CGMailREQ_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_kodgames_message_proto_mail_CGMailREQ_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_kodgames_message_proto_mail_CGMailREQ_descriptor,
              new java.lang.String[] { "Time", });
          internal_static_com_kodgames_message_proto_mail_GCMailRES_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_kodgames_message_proto_mail_GCMailRES_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_kodgames_message_proto_mail_GCMailRES_descriptor,
              new java.lang.String[] { "LastCheckTime", "OldCheckTime", "Mails", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
