//This file is generated by program. Do not edit it manually.

package com.kodgames.message.protocol;
import com.kodgames.message.generaor.ProtocolConfigAnnotation;

public class PlatformProtocolsConfig extends PlatformProtocols
{
	//Client and Auth Protocols for Clients 0x0000xxxx, xxxx start from 0x0000
			

	//Auth Protocols for Interface 0x0001xxxx, xxxx start from 0x0000
			
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.auth.AuthProtoBuf.IAAccountAuthREQ.class, needLogin = false)
	final public static int P_IA_ACCOUNT_AUTH_REQ = 0x10001;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.auth.AuthProtoBuf.AIAccountAuthRES.class, needLogin = false)
	final public static int P_AI_ACCOUNT_AUTH_RES = 0x10002;
		final public static int AI_AUTH_SUCCESS = 0x110002;
		final public static int AI_AUTH_FAILED_INVALID_CHANNEL = 0x1010002;
		final public static int AI_AUTH_FAILED_INVALID_USERNAME = 0x1110002;
		final public static int AI_AUTH_FAILED_INVALID_ARGUMENTS = 0x1210002;
		final public static int AI_AUTH_FAILED_WX_INVALID_CODE = 0x1310002;
		final public static int AI_AUTH_FAILED_WX_INVALID_REFRESH_TOKEN = 0x1410002;
		final public static int AI_AUTH_FAILED_FORCE_UPDATE = 0x1510002;
		final public static int AI_AUTH_FAILED_UNKNOWN = 0x1610002;
		final public static int AI_AUTH_FAILED_FORBID_REGISTER = 0x1710002;
		final public static int AI_AUTH_FAILED_INVALID_DEVICEID = 0x1810002;
		final public static int AI_AUTH_FAILED_INVALID_APPCODE = 0x1910002;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.auth.AuthProtoBuf.AIMergePlayerInfoREQ.class, needLogin = false)
	final public static int P_AI_MERGE_PLAYER_INFO_REQ = 0x10003;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.auth.AuthProtoBuf.IAMergePlayerInfoRES.class, needLogin = false)
	final public static int P_IA_MERGE_PLAYER_INFO_RES = 0x10004;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.auth.AuthProtoBuf.IGMergePlayerInfoREQ.class, needLogin = false)
	final public static int P_IG_MERGE_PLAYER_INFO_REQ = 0x10005;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.auth.AuthProtoBuf.GIMergePlayerInfoRES.class, needLogin = false)
	final public static int P_GI_MERGE_PLAYER_INFO_RES = 0x10006;
		final public static int GI_MERGE_PLAYER_INFO_SUCCESS = 0x1010006;
		final public static int GI_MERGE_PLAYER_INFO_FAIL_NO_PLAYER_INFO = 0x1110006;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.auth.AuthProtoBuf.IAVersionUpdateREQ.class, needLogin = false)
	final public static int P_IA_VERSION_UPDATE_REQ = 0x10007;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.auth.AuthProtoBuf.AIVersionUpdateRES.class, needLogin = false)
	final public static int P_AI_VERSION_UPDATE_RES = 0x10008;
		final public static int AI_VERSION_UPDATE_SUCCESS = 0x1010008;
		final public static int AI_VERSION_UPDATE_FAIL_NO_CHANNEL_INFO = 0x1110008;
		final public static int AI_VERSION_UPDATE_FAIL_FORCE_UPDATE = 0x1210008;
		final public static int AI_VERSION_UPDATE_FAIL_MANUAL_UPDATE = 0x1310008;
		final public static int AI_VERSION_UPDATE_FAIL_REVIEW_VERSION = 0x1410008;

	//Interface Protocols for Clients and server 0x0002xxxx, xxxx start from 0x0000
			
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.auth.AuthProtoBuf.CIAccountAuthREQ.class, needLogin = false)
	final public static int P_CI_ACCOUNT_AUTH_REQ = 0x20001;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.auth.AuthProtoBuf.ICAccountAuthRES.class, needLogin = false)
	final public static int P_IC_ACCOUNT_AUTH_RES = 0x20002;
		final public static int IC_AUTH_SUCCESS = 0x1020002;
		final public static int IC_AUTH_FAILED_NO_AUTH_SERVER = 0x1120002;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.auth.AuthProtoBuf.CIVersionUpdateREQ.class, needLogin = false)
	final public static int P_CI_VERSION_UPDATE_REQ = 0x20003;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.auth.AuthProtoBuf.ICVersionUpdateRES.class, needLogin = false)
	final public static int P_IC_VERSION_UPDATE_RES = 0x20004;

	//Client and Game Protocols for Clients 0x0003xxxx, xxxx start from 0x0000
			
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.CGLoginREQ.class, needLogin = false)
	final public static int P_CG_LOGIN_REQ = 0x30001;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.GCLoginRES.class, needLogin = false)
	final public static int P_GC_LOGIN_RES = 0x30002;
		final public static int GC_LOGIN_SUCCESS = 0x130002;
		final public static int GC_LOGIN_FAILED = 0x1030002;
		final public static int GC_LOGIN_FAILED_INVALID_PARAM = 0x1130002;
		final public static int GC_LOGIN_FAILED_FORBID_ROLE = 0x1230002;
		final public static int GC_LOGIN_FAILED_INVALID_CHANNEL = 0x1330002;
		final public static int GC_LOGIN_FAILED_INVALID_PLAYER_INFO = 0x1430002;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.CGLogoutREQ.class, needLogin = false)
	final public static int P_CG_LOGOUT_REQ = 0x30003;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.GCLogoutRES.class, needLogin = false)
	final public static int P_GC_LOGOUT_RES = 0x30004;
		final public static int GC_LOGOUT_SUCCESS = 0x130004;
		final public static int GC_LOGOUT_FAILED = 0x1030004;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.CGCreateRoomREQ.class, needLogin = true)
	final public static int P_CG_CREATE_ROOM_REQ = 0x30005;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.GCCreateRoomRES.class, needLogin = false)
	final public static int P_GC_CREATE_ROOM_RES = 0x30006;
		final public static int GC_CREATE_ROOM_SUCCESS = 0x130006;
		final public static int GC_CREATE_ROOM_FAILED_ROOMCARD_NOT_ENOUGTH = 0x1030006;
		final public static int GC_CREATE_ROOM_FAILED_NO_BATTLE = 0x1130006;
		final public static int GC_CREATE_ROOM_FAILED_ALREADY_IN_ROOM = 0x1230006;
		final public static int GC_CREATE_ROOM_FAILED_CREATING = 0x1330006;
		final public static int GC_CREATE_ROOM_FAILED_INVALID_ROUND_COUNT = 0x1430006;
		final public static int GC_CREATE_ROOM_NO_LCA = 0x1530006;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.CGQueryBattleIdREQ.class, needLogin = true)
	final public static int P_CG_QUERY_BATTLEID_REQ = 0x30007;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.GCQueryBattleIdRES.class, needLogin = false)
	final public static int P_GC_QUERY_BATTLEID_RES = 0x30008;
		final public static int GC_QUERY_BATTLEID_SUCCESS = 0x130008;
		final public static int GC_QUERY_BATTLEID_FAILED_ROOM_NOT_EXIST = 0x1030008;
		final public static int GC_QUERY_BATTLEID_FAILED_CLUB_ROOM = 0x1130008;
		final public static int GC_QUERY_BATTLEID_FAILED_CARDCOUNT_NOT_ENOUGH = 0x1230008;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.CGHistoryREQ.class, needLogin = true)
	final public static int P_CG_HISTORY_REQ = 0x30009;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.GCHistoryRES.class, needLogin = false)
	final public static int P_GC_HISTORY_RES = 0x3000a;
		final public static int GC_HISTORY_SUCCESS = 0x13000a;
		final public static int GC_HISTORY_FAILED = 0x103000a;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.CGHistoryRoomREQ.class, needLogin = true)
	final public static int P_CG_HISTORY_ROOM_REQ = 0x3000b;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.GCHistoryRoomRES.class, needLogin = false)
	final public static int P_GC_HISTORY_ROOM_RES = 0x3000c;
		final public static int GC_HISTORY_ROOM_SUCCESS = 0x13000c;
		final public static int GC_HISTORY_ROOM_FAILED = 0x103000c;
		final public static int GC_HISTORY_FAILED_ROOM_HISTORY_NOT_EXIST = 0x113000c;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.mail.MailProtoBuf.GCNewMailSYNC.class, needLogin = false)
	final public static int P_GC_NEW_MAIL_SYNC = 0x3000d;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.mail.MailProtoBuf.CGMailREQ.class, needLogin = false)
	final public static int P_CG_MAIL_REQ = 0x3000e;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.mail.MailProtoBuf.GCMailRES.class, needLogin = false)
	final public static int P_GC_MAIL_RES = 0x3000f;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.marquee.MarqueeProtoBuf.GCMarqueeVersionSYNC.class, needLogin = false)
	final public static int P_GC_MARQUEE_VERSION_SYNC = 0x30010;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.marquee.MarqueeProtoBuf.CGMarqueeREQ.class, needLogin = false)
	final public static int P_CG_MARQUEE_REQ = 0x30011;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.marquee.MarqueeProtoBuf.GCMarqueeRES.class, needLogin = false)
	final public static int P_GC_MARQUE_RES = 0x30012;
		final public static int GC_MARQUEE_SUCCESS = 0x130012;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.notice.NoticeProtoBuf.GCNoticeVersionSYN.class, needLogin = false)
	final public static int P_GC_NOTICE_SYN = 0x30013;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.notice.NoticeProtoBuf.CGNoticeREQ.class, needLogin = false)
	final public static int P_CG_NOTICE_REQ = 0x30014;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.notice.NoticeProtoBuf.GCNoticeRES.class, needLogin = false)
	final public static int P_GC_NOTICE_RES = 0x30015;
		final public static int GC_NOTICE_SUCCESS = 0x130015;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.contact.ContactProtoBuf.CGContactREQ.class, needLogin = false)
	final public static int P_CG_CONTACT_REQ = 0x30016;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.contact.ContactProtoBuf.GCContactRES.class, needLogin = false)
	final public static int P_GC_CONTACT_RES = 0x30017;
		final public static int GC_CONTACT_SUCCESS = 0x130017;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.GCRoomCardModifySYNC.class, needLogin = false)
	final public static int P_GC_ROOMCARD_MODIFY_SYNC = 0x30018;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.GCKickoffSYNC.class, needLogin = false)
	final public static int P_GC_KICKOFF_SYNC = 0x30019;
		final public static int GC_KICKOFF_SAME_LOGIN = 0x1030019;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.GCAntiAddictionSYN.class, needLogin = false)
	final public static int P_GC_ANTI_ADDICTION_SYN = 0x3001a;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.CGInviterRoomInfoREQ.class, needLogin = false)
	final public static int P_CG_INVITER_ROOMINFO_REQ = 0x3001b;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.GCInviterRoomInfoRES.class, needLogin = false)
	final public static int P_GC_INVITER_ROOMINFO_RES = 0x3001c;
		final public static int GC_INVITER_ROOMINFO_SUCCEE = 0x103001c;
		final public static int GC_INVITER_ROOMINFO_FAILED_ROOM_NOT_EXIST = 0x113001c;
		final public static int GC_INVITER_ROOMINFO_FAILED_INVITER_NOT_EXIST = 0x123001c;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.activity.ActivityProtoBuf.CGActivityRankREQ.class, needLogin = false)
	final public static int P_CG_ACTIVITY_RANK_REQ = 0x3001d;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.activity.ActivityProtoBuf.GCActivityRankRES.class, needLogin = false)
	final public static int P_GC_ACTIVITY_RANK_RES = 0x3001e;
		final public static int GC_ACTIVITY_RANK_SUCCESS = 0x103001e;
		final public static int GC_ACTIVITY_FAILED_NOT_EXIST = 0x113001e;
		final public static int GC_ACTIVITY_FAILED_TOO_EARLY = 0x123001e;
		final public static int GC_ACTIVITY_FAILED_TOO_LATE = 0x133001e;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.activity.ActivityProtoBuf.CGQueryTurntableInfoREQ.class, needLogin = false)
	final public static int P_CG_QUERY_TURNTABLE_INFO_REQ = 0x3001f;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.activity.ActivityProtoBuf.GCQueryTurntableInfoRES.class, needLogin = false)
	final public static int P_GC_QUERY_TURNTABLE_INFO_RES = 0x30020;
		final public static int GC_QUERY_TURNTABLE_INFO_SUCCESS = 0x1030020;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.activity.ActivityProtoBuf.CGTurntableDrawREQ.class, needLogin = false)
	final public static int P_CG_TURNTABLE_DRAW_REQ = 0x30021;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.activity.ActivityProtoBuf.GCTurntableDrawRES.class, needLogin = false)
	final public static int P_GC_TURNTABLE_DRAW_RES = 0x30022;
		final public static int GC_TURNTABLE_DRAW_SUCCESS = 0x1030022;
		final public static int GC_TURNTABLE_DRAW_NO_MORE_ITEM = 0x1130022;
		final public static int GC_TURNTABLE_DRAW_INACTIVE = 0x1230022;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.activity.ActivityProtoBuf.CGShareTurntableRewardREQ.class, needLogin = false)
	final public static int P_CG_SHARE_TURNTABLE_REWARD_REQ = 0x30023;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.activity.ActivityProtoBuf.CGShareTurntableRewardRES.class, needLogin = false)
	final public static int P_GC_SHARE_TURNTABLE_REWARD_RES = 0x30024;
		final public static int GC_SHARE_TURNTABLE_REWARD_SUCCESS = 0x1030024;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.activity.ActivityProtoBuf.GCPlayerHasItemCountSYN.class, needLogin = false)
	final public static int P_GC_PLAYER_HAS_ITEM_COUNT_SYN = 0x30025;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.activity.ActivityProtoBuf.GCNewLimitedCostlessActivitySYN.class, needLogin = false)
	final public static int P_GC_NEW_LIMITED_COSTLESS_ACTIVITY_SYN = 0x30026;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.activity.ActivityProtoBuf.CGLimitedCostlessActivityREQ.class, needLogin = false)
	final public static int P_CG_LIMITED_COSTLESS_ACTIVITY_REQ = 0x30027;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.activity.ActivityProtoBuf.GCLimitedCostlessActivityRES.class, needLogin = false)
	final public static int P_GC_LIMITED_COSTLESS_ACTIVITY_RES = 0x30028;
		final public static int GC_LIMITED_COSTLESS_ACTIVITY_SUCCESS = 0x130028;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.CGTimeSynchronizationREQ.class, needLogin = false)
	final public static int P_GC_TIME_SYNCHRONIZATION_REQ = 0x30029;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.GCTimeSynchronizationRES.class, needLogin = false)
	final public static int P_GC_TIME_SYNCHRONIZATION_RES = 0x3002a;
		final public static int GC_TIME_SYNCHRONIZATION_SUCCESS = 0x13002a;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.notice.NoticeProtoBuf.GCMainNoticeRES.class, needLogin = false)
	final public static int P_GC_MAIN_NOTICE_RES = 0x3002b;
		final public static int GC_MAIN_NOTICE_SUCCESS = 0x13002b;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.notice.NoticeProtoBuf.CGMainNoticeREQ.class, needLogin = false)
	final public static int P_CG_MAIN_NOTICE_REQ = 0x3002c;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.CGSendPhoneNumberREQ.class, needLogin = false)
	final public static int P_CG_SNED_PHONE_NUMBER_REQ = 0x3002d;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.GCSendPhoneNumberRES.class, needLogin = false)
	final public static int P_CG_SNED_PHONE_NUMBER_RES = 0x3002e;
		final public static int GC_ERROR_SIGN_PN = 0x103002e;
		final public static int GC_AGENT_EXIST_PN = 0x113002e;
		final public static int GC_AGENT_TEMP_PN = 0x123002e;
		final public static int GC_ERROR_PHONE_PN = 0x133002e;
		final public static int GC_PHOHE_NUMBER_SUCCESS_PN = 0x13002e;
		final public static int GC_PHONE_NUMBER_PLAYER_EXIST_PN = 0x143002e;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.CGBindMobileREQ.class, needLogin = false)
	final public static int P_CG_BIND_MOBILE_REQ = 0x3002f;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.GCBindMobileRES.class, needLogin = false)
	final public static int P_GC_BIND_MOBILE_RES = 0x30030;
		final public static int GC_BIND_MOBILE_NO = 0x1030030;
		final public static int GC_BIND_MOBILE_YES = 0x1130030;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.CGSendBindCodeREQ.class, needLogin = false)
	final public static int P_CG_SEND_BIND_CODE_REQ = 0x30031;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.GCSendBindCodeRES.class, needLogin = false)
	final public static int P_GC_SEND_BIND_CODE_RES = 0x30032;
		final public static int GC_SEND_BIND_CODE_SUCCESS = 0x1030032;
		final public static int GC_SEND_BIND_CODE_FAIL = 0x1130032;
		final public static int GC_SEND_BIND_CODE_LIMIT = 0x1230032;
		final public static int GC_SEND_BIND_CODE_BIND_BEFORE = 0x1330032;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.CGBindValidREQ.class, needLogin = false)
	final public static int P_CG_BIND_VAILD_REQ = 0x30033;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.GCBindValidRES.class, needLogin = false)
	final public static int P_GC_BIND_VAILD_RES = 0x30034;
		final public static int GC_BIND_VAILD_OK = 0x1030034;
		final public static int GC_BIND_VAILD_ERROR = 0x1130034;
		final public static int GC_BIND_VAILD_OVERTIME = 0x1230034;
		final public static int GC_NOT_GET_CODE = 0x1330034;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.CGSendVerificationCodeREQ.class, needLogin = false)
	final public static int P_CG_SNED_VERIFICATION_CODE_REQ = 0x30035;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.GCSendVerificationCodeRES.class, needLogin = false)
	final public static int P_CG_SNED_VERIFICATION_CODE_RES = 0x30036;
		final public static int GC_ERROR_SIGN_VC = 0x1030036;
		final public static int GC_AGENT_EXIST_VC = 0x1130036;
		final public static int GC_AGENT_TEMP_VC = 0x1230036;
		final public static int GC_ERROR_PHONE_VC = 0x1330036;
		final public static int GC_EXRIPE_VERIYCODE_VC = 0x1430036;
		final public static int GC_ERROR_VERIFYCODE_VC = 0x1530036;
		final public static int GC_PHOHE_NUMBER_SUCCESS_VC = 0x130036;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.CGQueryPromoterRewardsREQ.class, needLogin = false)
	final public static int P_CG_QUERY_PROMOTER_REWARDS_REQ = 0x30037;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.GCQueryPromoterRewardsRES.class, needLogin = false)
	final public static int P_GC_QUERY_PROMOTER_REWARD_RES = 0x30038;
		final public static int GC_QUERY_PROMOTER_REWARD_SUCCESS = 0x130038;
		final public static int GC_QUERY_PROMOTER_REWARD_FAILED_ACTIVITY_INACTIVE = 0x1030038;
		final public static int GC_QUERY_PROMOTER_REWARD_FAILED_PROMOTER_ABSENT = 0x1130038;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.CGPromoterRewardREQ.class, needLogin = false)
	final public static int P_CG_PROMOTER_REWARD_REQ = 0x30039;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.GCPromoterRewardRES.class, needLogin = false)
	final public static int P_GC_PROMOTER_REWARD_RES = 0x3003a;
		final public static int GC_PROMOTER_REWARD_SUCCESS = 0x13003a;
		final public static int GC_PROMOTER_REWARD_FAILED_ACTIVITY_INACTIVE = 0x103003a;
		final public static int GC_PROMOTER_REWARD_FAILED = 0x113003a;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.CGPromoterShareREQ.class, needLogin = false)
	final public static int P_CG_PROMOTER_SHARE_REQ = 0x3003b;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.GCPromoterShareRES.class, needLogin = false)
	final public static int P_GC_PROMOTER_SHARE_RES = 0x3003c;
		final public static int GC_PROMOTER_SHARE_SUCCESS = 0x13003c;
		final public static int GC_PROMOTER_SHARE_FAILED = 0x103003c;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.CGPopUpMessageInfoREQ.class, needLogin = false)
	final public static int P_CG_POP_UP_MESSAGE_INFO_REQ = 0x3003d;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.GCPopUpMessageInfoRES.class, needLogin = false)
	final public static int P_CG_POP_UP_MESSAGE_INFO_RES = 0x3003e;
		final public static int GC_POP_UP_MESSAGE_INFO_RES_SUCCESS = 0x13003e;
		final public static int GC_POP_UP_MESSAGE_INFO_RES_VERSION_SAME = 0x103003e;
		final public static int GC_POP_UP_MESSAGE_INFO_RES_FAILED_MESSAGE_IS_ABSENT = 0x113003e;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.GCPopUpMessageInfoSYN.class, needLogin = false)
	final public static int P_GC_POP_UP_MESSAGE_INFO_SYNC = 0x3003f;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.CGContinueRoomREQ.class, needLogin = true)
	final public static int P_CG_CONTINUE_ROOM_REQ = 0x30040;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.GCContinueRoomRES.class, needLogin = false)
	final public static int P_GC_CONTINUE_ROOM_RES = 0x30041;
		final public static int GC_CONTINUE_ROOM_SUCCESS = 0x130041;
		final public static int GC_CONTINUE_ROOM_FAILED_ROOMCARD_NOT_ENOUGTH = 0x1030041;
		final public static int GC_CONTINUE_ROOM_FAILED_NO_BATTLE = 0x1130041;
		final public static int GC_CONTINUE_ROOM_FAILED_ALREADY_IN_ROOM = 0x1230041;
		final public static int GC_CONTINUE_ROOM_FAILED_CREATING = 0x1330041;
		final public static int GC_CONTINUE_ROOM_FAILED_INVALID_ROUND_COUNT = 0x1430041;
		final public static int GC_CONTINUE_ROOM_FAILED_NO_OLD_ROOM = 0x1530041;
		final public static int GC_CONTINUE_ROOM_NO_LCA = 0x1630041;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.CGContinueEnterRoomREQ.class, needLogin = true)
	final public static int P_CG_CONTINUE_ENTER_ROOM_REQ = 0x30042;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.GCContinueEnterRoomRES.class, needLogin = false)
	final public static int P_GC_CONTINUE_ENTER_ROOM_RES = 0x30043;
		final public static int GC_CONTINUE_ENTER_ROOM_SUCCESS = 0x130043;
		final public static int GC_CONTINUE_ENTER_ROOM_FAILED_ROOMCARD_NOT_ENOUGTH = 0x1030043;
		final public static int GC_CONTINUE_ENTER_ROOM_FAILED_CLUB_ROOM = 0x1130043;
		final public static int GC_CONTINUE_ENTER_ROOM_FAILED_ROOM_NOT_EXIST = 0x1230043;
		final public static int GC_CONTINUE_ENTER_ROOM_FAILED_ROOM_FULL = 0x1330043;
		final public static int GC_CONTINUE_ENTER_ROOM_FAILED_NO_OLD_ROOM = 0x1430043;
		final public static int GC_CONTINUE_ENTER_ROOM_CONNECTION_ERROR = 0x1530043;

	//Client and Battle Protocols for Clients 0x0004xxxx, xxxx start from 0x0000
			
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.room.RoomProtoBuf.CBEnterRoomREQ.class, needLogin = false)
	final public static int P_CB_ENTER_ROOM_REQ = 0x40001;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.room.RoomProtoBuf.BCEnterRoomRES.class, needLogin = false)
	final public static int P_BC_ENTER_ROOM_RES = 0x40002;
		final public static int BC_ENTER_ROOM_SUCCESS = 0x140002;
		final public static int BC_ENTER_ROOM_FAILED = 0x1040002;
		final public static int BC_ENTER_ROOM_FAILED_ROOM_NOT_EXIST = 0x1140002;
		final public static int BC_ENTER_ROOM_FAILED_ROOM_FULL = 0x1240002;
		final public static int BC_ENTER_ROOM_FAILED_MEMBERS_ERROR = 0x1340002;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.room.RoomProtoBuf.BCRoomPlayerInfoSYN.class, needLogin = false)
	final public static int P_BC_ROOM_PLAYERINFO_SYN = 0x40003;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.room.RoomProtoBuf.CBQuitRoomREQ.class, needLogin = true)
	final public static int P_CB_QUIT_ROOM_REQ = 0x40004;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.room.RoomProtoBuf.BCQuitRoomRES.class, needLogin = false)
	final public static int P_BC_QUIT_ROOM_RES = 0x40005;
		final public static int BC_QUIT_ROOM_SUCCESS = 0x140005;
		final public static int BC_QUIT_ROOM_FAILED = 0x1040005;
		final public static int BC_QUIT_ROOM_FAILED_NOT_IN_ROOM = 0x1140005;
		final public static int BC_QUIT_ROOM_FAILED_IN_BATTLE = 0x1240005;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.room.RoomProtoBuf.CBStartVoteDestroyREQ.class, needLogin = true)
	final public static int P_CB_START_VOTE_DESTROY_REQ = 0x40006;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.room.RoomProtoBuf.BCStartVoteDestroyRES.class, needLogin = false)
	final public static int P_BC_START_VOTE_DESTROY_RES = 0x40007;
		final public static int BC_START_VOTE_SUCCESS = 0x140007;
		final public static int BC_START_VOTE_FAILED_NOT_IN_ROOM = 0x1040007;
		final public static int BC_START_VOTE_FAILED_WITHOUT_BATTLE = 0x1140007;
		final public static int BC_START_VOTE_FAILED_VOTING = 0x1240007;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.room.RoomProtoBuf.CBVoteDestroyREQ.class, needLogin = true)
	final public static int P_CB_VOTE_DESTROY_REQ = 0x40008;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.room.RoomProtoBuf.BCVoteDestroyRES.class, needLogin = false)
	final public static int P_BC_VOTE_DESTROY_RES = 0x40009;
		final public static int BC_VOTE_DESTROY_SUCCESS = 0x140009;
		final public static int BC_VOTE_DESTROY_FAILED_NOT_IN_ROOM = 0x1040009;
		final public static int BC_VOTE_DESTROY_FAILED_HAS_VOTED = 0x1140009;
		final public static int BC_VOTE_DESTROY_FAILED_WITHOUT_BATTLE = 0x1240009;
		final public static int BC_VOTE_DESTROY_FAILED_WITHOUT_VOTE = 0x1340009;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.room.RoomProtoBuf.BCVoteDestroyInfoSYN.class, needLogin = false)
	final public static int P_BC_VOTE_DESTROYINFO_SYN = 0x4000a;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.room.RoomProtoBuf.BCDestroyRoomSYN.class, needLogin = false)
	final public static int P_BC_DESTROY_ROOM_SYN = 0x4000b;
		final public static int BC_DESTROY_ROOM_VOTE = 0x14000b;
		final public static int BC_DESTROY_ROOM_GMT = 0x24000b;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.room.RoomProtoBuf.CBUpdateStatusREQ.class, needLogin = false)
	final public static int P_CB_UPDATE_PLAYERSTATUS_REQ = 0x4000c;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.room.RoomProtoBuf.BCUpdateStatusRES.class, needLogin = false)
	final public static int P_BC_UPDATE_PLAYERSTATUS_RES = 0x4000d;
		final public static int BC_UPDATE_PLAYERSTATUS_SUCCESS = 0x14000d;
		final public static int BC_UPDATE_PLAYERSTATUS_FAILED_NOT_IN_ROOM = 0x104000d;
		final public static int BC_UPDATE_PLAYERSTATUS_FAILED_INVALID_STATUS = 0x114000d;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.battle.BattleProtoBuf.BCBattlePlayerInfoSYN.class, needLogin = false)
	final public static int P_BC_BATTLE_PLAYERINFO_SYN = 0x4000e;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.battle.BattleProtoBuf.BCPlayStepSYN.class, needLogin = false)
	final public static int P_BC_PLAYSTEP_SYN = 0x4000f;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.battle.BattleProtoBuf.CBPlayCardREQ.class, needLogin = false)
	final public static int P_CB_PLAYCARD_REQ = 0x40010;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.battle.BattleProtoBuf.BCPlayCardRES.class, needLogin = false)
	final public static int P_BC_PLAYCARD_RES = 0x40011;
		final public static int BC_PLAYCARD_SUCCESS = 0x140011;
		final public static int BC_PLAYCARD_FAILED_NOT_IN_ROOM = 0x1040011;
		final public static int BC_PLAYCARD_FAILED_NOT_HAVE_THIS_CARD = 0x1140011;
		final public static int BC_PLAYCARD_FAILED_NOT_MATCH_THIS_CARD = 0x1240011;
		final public static int BC_PLAYCARD_FAILED_NOT_YOUR_TURN = 0x1340011;
		final public static int BC_PLAYCARD_FAILED_NOT_VALID_ROLEID = 0x1440011;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.battle.BattleProtoBuf.BCMatchResultSYN.class, needLogin = false)
	final public static int P_BC_MATCHRESULT_SYN = 0x40012;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.battle.BattleProtoBuf.BCFinalMatchResultSYN.class, needLogin = false)
	final public static int P_BC_FINALMATCHRESULT_SYN = 0x40013;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.chat.ChatProtoBuf.CBChatREQ.class, needLogin = false)
	final public static int P_CB_CHAT_REQ = 0x40014;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.chat.ChatProtoBuf.BCChatRES.class, needLogin = false)
	final public static int P_BC_CHAT_RES = 0x40015;
		final public static int BC_CHAT_SUCCESS = 0x140015;
		final public static int BC_CHAT_FAILED_NOT_IN_ROOM = 0x1040015;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.chat.ChatProtoBuf.BCChatSYN.class, needLogin = false)
	final public static int P_BC_CHAT_SYN = 0x40016;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.room.RoomProtoBuf.BCSameIpSYN.class, needLogin = false)
	final public static int P_BC_SAME_IP_SYN = 0x40017;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.chat.ChatProtoBuf.CBAnimationREQ.class, needLogin = false)
	final public static int P_CB_ANIMATION_REQ = 0x40018;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.chat.ChatProtoBuf.BCAnimationRES.class, needLogin = false)
	final public static int P_BC_ANIMATION_RES = 0x40019;
		final public static int BC_ANIMATION_SUCCESS = 0x140019;
		final public static int BC_ANIMATION_FAILED_NOT_IN_ROOM = 0x1040019;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.chat.ChatProtoBuf.BCAnimationSYN.class, needLogin = false)
	final public static int P_BC_ANIMATION_SYN = 0x4001a;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.room.RoomProtoBuf.CBGpsInfoREQ.class, needLogin = false)
	final public static int P_CB_GPS_INFO_REQ = 0x4001b;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.room.RoomProtoBuf.BCGpsInfoRES.class, needLogin = false)
	final public static int P_BC_GPS_INFO_RES = 0x4001c;
		final public static int BC_GPS_INFO_SUCCESS = 0x14001c;
		final public static int BC_GPS_INFO_FAILED_NOT_IN_ROOM = 0x104001c;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.room.RoomProtoBuf.BCSecureDetectSYN.class, needLogin = false)
	final public static int P_BC_SECUREDETECTSYN_RES = 0x4001d;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.room.RoomProtoBuf.BCIsContinueRoomSYN.class, needLogin = false)
	final public static int P_BC_IS_CONTINUE_ROOM_SYN = 0x4001e;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.room.RoomProtoBuf.BCContinueRoomPlayerInfoSYN.class, needLogin = false)
	final public static int P_BC_CONTINUE_ROOM_PLAYER_INFO_SYN = 0x4001f;

	//Game and Battle Protocols for Clients 0x0005xxxx, xxxx start from 0x0000
			
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.GBCreateRoomREQ.class, needLogin = false)
	final public static int P_GB_CREATE_ROOM_REQ = 0x50001;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.BGCreateRoomRES.class, needLogin = false)
	final public static int P_BG_CREATE_ROOM_RES = 0x50002;
		final public static int BG_CREATE_ROOM_SUCCESS = 0x150002;
		final public static int BG_CREATE_ROOM_FAILED = 0x1050002;
		final public static int BG_CREATE_ROOM_FAILED_ROOM_EXIST = 0x1150002;
		final public static int BG_CREATE_ROOM_FAILED_INVALID_GAMEPLAYS = 0x1250002;
		final public static int BG_CREATE_ROOM_FAILED_INVALID_ROUNDCOUNT = 0x1350002;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.BGEnterRoomSYN.class, needLogin = false)
	final public static int P_BG_ENTER_ROOM_SYN = 0x50003;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.BGQuitRoomSYN.class, needLogin = false)
	final public static int P_BG_QUIT_ROOM_SYN = 0x50004;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.BGDestroyRoomSYN.class, needLogin = false)
	final public static int P_BG_DESTROY_ROOM_SYN = 0x50005;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.BGRoomCardModifySYNC.class, needLogin = false)
	final public static int P_BG_ROOMCARD_MODIFY_SYN = 0x50006;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.BGMatchResultSYN.class, needLogin = false)
	final public static int P_BG_MATCH_RESULT_SYN = 0x50007;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.BGBattleStatisticsSYN.class, needLogin = false)
	final public static int P_BG_ROOM_STATUS_SYN = 0x50008;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.record.RecordProtoBuf.BGRecordLogSYN.class, needLogin = false)
	final public static int P_BG_RECORD_LOG_SYN = 0x50009;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.GBGmtDestroyRoomSYN.class, needLogin = false)
	final public static int P_GB_FORCE_DESTROY_ROOM_SYN = 0x5000a;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.GBGameConfigSYN.class, needLogin = false)
	final public static int P_GB_GAME_CONFIG_SYN = 0x5000b;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.GCLGameConfigSYN.class, needLogin = false)
	final public static int P_GCL_GAME_CONFIG_SYN = 0x5000c;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.GBInviterRoomInfoREQ.class, needLogin = false)
	final public static int P_GB_INVITER_ROOMINFO_REQ = 0x5000d;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.BGInviterRoomInfoRES.class, needLogin = false)
	final public static int P_BG_INVITER_ROOMINFO_RES = 0x5000e;
		final public static int BG_INVITER_ROOMINFO_SUCCEE = 0x105000e;
		final public static int BG_INVITER_ROOMINFO_FAILED_ROOM_NOT_EXIST = 0x115000e;
		final public static int BG_INVITER_ROOMINFO_FAILED_INVITER_NOT_EXIST = 0x125000e;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.BGFinalMatchResultSYN.class, needLogin = false)
	final public static int P_BG_FINAL_MATCH_RESULT_SYN = 0x5000f;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.CGJoinRoleInfoREQ.class, needLogin = false)
	final public static int P_CG_JOIN_ROLEINFO_REQ = 0x50010;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.GCJoinRoleInfoRES.class, needLogin = false)
	final public static int P_GC_JOIN_ROLEINFO_RES = 0x50011;
		final public static int GC_JOIN_ROLEINFO_SUCCEE = 0x1050011;
		final public static int GC_JOIN_ROLEINFO_ROLE_NOT_FOUND = 0x1150011;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.GBContinueRoomREQ.class, needLogin = false)
	final public static int P_GB_CONTINUE_ROOM_REQ = 0x50012;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.BGContinueRoomRES.class, needLogin = false)
	final public static int P_BG_CONTINUE_ROOM_RES = 0x50013;
		final public static int BG_CONTINUE_ROOM_SUCCESS = 0x150013;
		final public static int BG_CONTINUE_ROOM_FAILED = 0x1050013;
		final public static int BG_CONTINUE_ROOM_FAILED_ROOM_EXIST = 0x1150013;
		final public static int BG_CONTINUE_ROOM_FAILED_INVALID_GAMEPLAYS = 0x1250013;
		final public static int BG_CONTINUE_ROOM_FAILED_INVALID_ROUNDCOUNT = 0x1350013;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.GBContinueEnterRoomREQ.class, needLogin = true)
	final public static int P_GB_CONTINUE_ENTER_ROOM_REQ = 0x50014;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.BGContinueEnterRoomRES.class, needLogin = false)
	final public static int P_BG_CONTINUE_ENTER_ROOM_RES = 0x50015;
		final public static int BG_CONTINUE_ENTER_ROOM_SUCCESS = 0x150015;
		final public static int BG_CONTINUE_ENTER_ROOM_FAILED_ROOM_NOT_EXIST = 0x1050015;
		final public static int BG_CONTINUE_ENTER_ROOM_FAILED_ROOM_FULL = 0x1150015;
		final public static int BG_CONTINUE_ENTER_ROOM_CONNECTION_ERROR = 0x1250015;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.GBContinueEnterRoomOverSYN.class, needLogin = false)
	final public static int P_BG_CONTINUE_ENTER_ROOM_OVER_SYN = 0x50016;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.CGHistoryPlaybackREQ.class, needLogin = true)
	final public static int P_CG_HISTORY_PLAYBACK_REQ = 0x50017;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.game.GameProtoBuf.GCHistoryPlaybackRES.class, needLogin = false)
	final public static int P_GC_HISTORY_PLAYBACK_RES = 0x50018;
		final public static int GC_HISTORY_PLAYBACK_SUCCESS = 0x150018;
		final public static int GC_HISTORY_PLAYBACK_FAILED = 0x1050018;

	//Protocols for Servers 0x0006xxxx, xxxx start from 0x0000
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.server.ServerProtoBuf.SSGetLaunchInfoREQ.class, needLogin = false)
	final public static int P_SS_GET_LAUNCH_INFO_REQ = 0x60001;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.server.ServerProtoBuf.SSGetLaunchInfoRES.class, needLogin = false)
	final public static int P_SS_GETLAUNCH_INFO_RES = 0x60002;
		final public static int SS_GET_LAUNCH_INFO_SUCCESS = 0x160002;
		final public static int SS_GET_LAUNCH_INFO_FAILED = 0x1060002;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.server.ServerProtoBuf.SSRegisterServerREQ.class, needLogin = false)
	final public static int P_SS_REGISTER_SERVER_REQ = 0x60003;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.server.ServerProtoBuf.SSServerListSYNC.class, needLogin = false)
	final public static int P_SS_SERVER_LIST_SYNC = 0x60004;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.server.ServerProtoBuf.SSServerDisconnectSYNC.class, needLogin = false)
	final public static int P_SS_SERVER_DISCONNECT_SYNC = 0x60005;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.server.ServerProtoBuf.ClientDisconnectSYN.class, needLogin = false)
	final public static int P_CLIENT_DISCONNECT_SYN = 0x60006;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.server.ServerProtoBuf.SSExchangePeerInfoSYNC.class, needLogin = false)
	final public static int P_SS_EXCHANGE_PEER_INFO_SYN = 0x60007;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.server.ServerProtoBuf.PlatformPurchaseREQ.class, needLogin = false)
	final public static int P_PLATFORM_PURCHASE_REQ = 0x60008;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.server.ServerProtoBuf.PlatformPurchaseRES.class, needLogin = false)
	final public static int P_PLATFORM_PURCHASE_RES = 0x60009;
		final public static int SS_PLATFORM_PURCHASE_SUCCESS = 0x160009;
		final public static int SS_PLATFORM_PURCHASE_FAILED = 0x1060009;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.server.ServerProtoBuf.PlatformAgentPurchaseREQ.class, needLogin = false)
	final public static int P_PLATFORM_AGENT_PURCHASE_REQ = 0x6000a;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.server.ServerProtoBuf.PlatformAgentPurchaseRES.class, needLogin = false)
	final public static int P_PLATFORM_AGENT_PURCHASE_RES = 0x6000b;
		final public static int SS_PLATFORM_AGENT_PURCHASE_SUCCESS = 0x16000b;
		final public static int SS_PLATFORM_AGENT_PURCHASE_FAILED = 0x106000b;

	//Protocols for Clients 0x0007xxxx, xxxx start from 0x0000
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.server.ServerProtoBuf.ServerExceptionSYNC.class, needLogin = false)
	final public static int P_SERVER_EXCEPTION_SYNC = 0x70001;

	//Club Protocols for Clients and server 0x0008xxxx, xxxx start from 0x0000
			
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.CCLCreateRoomREQ.class, needLogin = false)
	final public static int P_CCL_CREATE_ROOM_REQ = 0x80001;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.CLCCreateRoomRES.class, needLogin = false)
	final public static int P_CLC_CREATE_ROOM_RES = 0x80002;
		final public static int CLC_CREATE_ROOM_SUCCESS = 0x1080002;
		final public static int CLC_CREATE_ROOM_FAILED_NO_SUCH_CLUB = 0x1180002;
		final public static int CLC_CREATE_ROOM_FAILED_NO_RIGHT = 0x1280002;
		final public static int CLC_CREATE_ROOM_FAILED_NOT_ENOUGH_CARDS = 0x1380002;
		final public static int CLC_CREATE_ROOM_FAILED_MANAGER_NOT_ENOUGH_CARDS = 0x1480002;
		final public static int CLC_CREATE_ROOM_FAILED_CLUB_SEALED = 0x1580002;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.CLGCreateRoomREQ.class, needLogin = false)
	final public static int P_CLG_CREATE_ROOM_REQ = 0x80003;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.GCLCreateRoomRES.class, needLogin = false)
	final public static int P_GCL_CREATE_ROOM_REQ = 0x80004;
		final public static int GCL_CREATE_ROOM_SUCCESS = 0x1080004;
		final public static int GCL_CREATE_ROOM_FAILED_ROOM_EXIST = 0x1180004;
		final public static int GCL_CREATE_ROOM_FAILED_CREATING = 0x1280004;
		final public static int GCL_CREATE_ROOM_FAILED_ALREADY_IN_ROOM = 0x1380004;
		final public static int GCL_CREATE_ROOM_FAILED_NO_BATTLE = 0x1480004;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.CCLEnterRoomREQ.class, needLogin = false)
	final public static int P_CCL_ENTER_ROOM_REQ = 0x80005;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.CLCEnterRoomRES.class, needLogin = false)
	final public static int P_CLC_ENTER_ROOM_RES = 0x80006;
		final public static int CLC_ENTER_ROOM_SUCCESS = 0x1080006;
		final public static int CLC_ENTER_ROOM_FAILED_NO_SUCH_ROOM = 0x1180006;
		final public static int CLC_ENTER_ROOM_NOT_IN_CLUB = 0x1280006;
		final public static int CLC_ENTER_ROOM_FAILED_NO_RIGHT = 0x1380006;
		final public static int CLC_ENTER_ROOM_FAILED_NOT_ENOUGH_CARDS = 0x1480006;
		final public static int CLC_ENTER_ROOM_FAILED_CLUB_SEALED = 0x1580006;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.GCLEnterRoomSYN.class, needLogin = false)
	final public static int P_GCL_ENTER_ROOM_SYN = 0x80007;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.GCLQuitRoomSYN.class, needLogin = false)
	final public static int P_GCL_QUIT_ROOM_SYN = 0x80008;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.GCLDestroyRoomSYN.class, needLogin = false)
	final public static int P_GCL_DESTROY_ROOM_SYN = 0x80009;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.GCLGmtDestroyRoomSYN.class, needLogin = false)
	final public static int P_GCL_GMT_DESTROY_ROOM_SYN = 0x8000a;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.CLCClubRoomCardModifySYN.class, needLogin = false)
	final public static int P_CCL_CLUB_ROOM_CARD_MODIFY_SYN = 0x8000b;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.GCLEnableSubCardSYN.class, needLogin = false)
	final public static int P_GCL_ENABLE_SUB_CARD_SYN = 0x8000c;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.GCLMatchResultSYN.class, needLogin = false)
	final public static int P_GCL_MATCH_RESULT_SYN = 0x8000d;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.GCLFinalMatchResultSYN.class, needLogin = false)
	final public static int P_GCL_FINAL_MATCH_RESULT_SYN = 0x8000e;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.CCLClubInfoREQ.class, needLogin = false)
	final public static int P_CCL_CLUB_INFO_REQ = 0x8000f;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.CLCClubInfoRES.class, needLogin = false)
	final public static int P_CLC_CLUB_INFO_RES = 0x80010;
		final public static int CLC_CLUB_INFO_SUCCESS = 0x180010;
		final public static int CLC_CLUB_NOT_FOUND = 0x1080010;
		final public static int CLC_CLUB_SEALED = 0x1180010;
		final public static int CLC_CLUB_WRONG_CODE = 0x1280010;
		final public static int CLC_CLUB_KICK_OUT = 0x1380010;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.CCLJoinClubInfoREQ.class, needLogin = false)
	final public static int P_CCL_JOIN_CLUB_INFO_REQ = 0x80011;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.CLCJoinClubInfoRES.class, needLogin = false)
	final public static int P_CLC_JOIN_CLUB_INFO_RES = 0x80012;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.CCLJoinClubREQ.class, needLogin = false)
	final public static int P_CCL_CLUB_JOIN_REQ = 0x80013;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.CLCJoinClubRES.class, needLogin = false)
	final public static int P_CLC_CLUB_JOIN_RES = 0x80014;
		final public static int CLC_CLUB_JOIN_SUCCESS = 0x180014;
		final public static int CLC_CLUB_JOIN_ALREADY_JOINED = 0x1080014;
		final public static int CLC_CLUB_JOIN_ALREADY_JOINED_APPLICANT = 0x1180014;
		final public static int CLC_CLUB_JOIN_NOT_PERMITTED = 0x1280014;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.CCLQuitClubREQ.class, needLogin = false)
	final public static int P_CCL_CLUB_QUIT_REQ = 0x80015;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.CLCQuitClubRES.class, needLogin = false)
	final public static int P_CLC_CLUB_QUIT_RES = 0x80016;
		final public static int CLC_CLUB_QUIT_SUCCESS = 0x180016;
		final public static int CLC_CLUB_QUIT_NOT_IN_CLUB = 0x1080016;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.CCLClubMembersREQ.class, needLogin = false)
	final public static int P_CCL_CLUB_MEMBERS_REQ = 0x80017;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.CLCClubMembersRES.class, needLogin = false)
	final public static int P_CLC_CLUB_MEMBERS_RES = 0x80018;
		final public static int CLC_CLUB_MEMBERS_SUCCESS = 0x180018;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.CCLClubNoticeModifyREQ.class, needLogin = false)
	final public static int P_CCL_CLUB_NOTICEMODIFY_REQ = 0x80019;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.CLCClubNoticeModifyRES.class, needLogin = false)
	final public static int P_CLC_CLUB_NOTICEMODIFY_RES = 0x8001a;
		final public static int CLC_CLUB_NOTICEMODIFY_SUCCESS = 0x18001a;
		final public static int CLC_CLUB_NOTICEMODIFY_CLUB_NOT_FOUND = 0x108001a;
		final public static int CLC_CLUB_NOTICEMODIFY_NOT_PERMITED = 0x118001a;
		final public static int CLC_CLUB_NOTICEMODIFY_TEXT_TOO_LONG = 0x128001a;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.CCLClubCostModifyREQ.class, needLogin = false)
	final public static int P_CCL_CLUB_COSTMODIFY_REQ = 0x8001b;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.CLCClubCostModifyRES.class, needLogin = false)
	final public static int P_CLC_CLUB_COSTMODIFY_RES = 0x8001c;
		final public static int CLC_CLUB_COSTMODIFY_SUCCESS = 0x18001c;
		final public static int CLC_CLUB_COSTMODIFY_CLUB_NOT_FOUND = 0x108001c;
		final public static int CLC_CLUB_COSTMODIFY_NOT_PERMITED = 0x118001c;
		final public static int CLC_CLUB_COSTMODIFY_ARGS_ERROR = 0x128001c;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.CCLClubMemberModifyREQ.class, needLogin = false)
	final public static int P_CCL_CLUB_MEMBERMODIFY_REQ = 0x8001d;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.CLCClubMemberModifyRES.class, needLogin = false)
	final public static int P_CLC_CLUB_MEMBERMODIFY_RES = 0x8001e;
		final public static int CLC_CLUB_MEMBERMODIFY_SUCCESS = 0x18001e;
		final public static int CLC_CLUB_MEMBERMODIFY_NOT_PERMITED = 0x108001e;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.CCLClubApplicantListREQ.class, needLogin = false)
	final public static int P_CCL_CLUB_APPLICANTS_REQ = 0x8001f;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.CLCClubApplicantListRES.class, needLogin = false)
	final public static int P_CLC_CLUB_APPLICANTS_RES = 0x80020;
		final public static int CLC_CLUB_APPLICANTS_SUCCESS = 0x180020;
		final public static int CLC_CLUB_APPLICANTS_CLUB_NOT_FOUND = 0x1080020;
		final public static int CLC_CLUB_APPLICANTS_NOT_PERMITED = 0x1180020;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.CCLClubApplicantREQ.class, needLogin = false)
	final public static int P_CCL_CLUB_APPLICANT_REQ = 0x80021;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.CLCClubApplicantRES.class, needLogin = false)
	final public static int P_CLC_CLUB_APPLICANT_RES = 0x80022;
		final public static int CLC_CLUB_APPLICANT_SUCCESS = 0x180022;
		final public static int CLC_CLUB_APPLICANT_CLUB_NOT_FOUND = 0x1080022;
		final public static int CLC_CLUB_APPLICANT_NOT_PERMITED = 0x1180022;
		final public static int CLC_CLUB_APPLICANT_NOT_IN_LIST = 0x1280022;
		final public static int CLC_CLUB_APPLICANT_MAX_CLUBS = 0x1380022;
		final public static int CLC_CLUB_APPLICANT_MAX_MEMBERS = 0x1480022;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.CCLAllClubREQ.class, needLogin = false)
	final public static int P_CCL_ALL_CLUB_REQ = 0x80023;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.CLCAllClubRES.class, needLogin = false)
	final public static int P_CLC_ALL_CLUB_RES = 0x80024;
		final public static int CLC_ALL_CLUB_SUCCESS = 0x180024;
		final public static int CLC_ALL_CLUB_NOT_IN_ANY_CLUB = 0x1080024;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.CCLClubTableREQ.class, needLogin = false)
	final public static int P_CCL_CLUB_TABLE_REQ = 0x80025;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.CLCClubTableRES.class, needLogin = false)
	final public static int P_CLC_CLUB_TABLE_RES = 0x80026;
		final public static int CLC_CLUB_TABLE_SUCCESS = 0x180026;
		final public static int CLC_CLUB_TABLE_NOT_IN_ANY_CLUB = 0x1080026;
		final public static int CLC_CLUB_TABLE_NOT_IN_THIS_CLUB = 0x1180026;
		final public static int CLC_CLUB_TABLE_ROOMS_NOT_FOUND = 0x1280026;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.CLGCheckRoleInfoREQ.class, needLogin = false)
	final public static int P_CLG_CHECK_ROLE_INFO_REQ = 0x80027;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.GCLCheckRoleInfoRES.class, needLogin = false)
	final public static int P_GCL_CHECK_ROLE_INFO_RES = 0x80028;
		final public static int GCL_CHECK_ROLE_INFO_SUCCESS = 0x180028;
		final public static int GCL_CHECK_ROLE_INFO_ROLE_NOT_FOUND = 0x1080028;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.GCLLoginSYN.class, needLogin = false)
	final public static int P_GCL_LOGIN_SYN = 0x80029;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.CLGBroadcastMSG.class, needLogin = false)
	final public static int P_CLG_BROADCARD_MSG = 0x8002a;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.CLCApplicantCountRES.class, needLogin = false)
	final public static int P_CLC_APPLICANT_COUNT_RES = 0x8002b;
		final public static int CLC_APPLICANT_COUNT_SUCCESS = 0x18002b;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.CCLApplicantCountREQ.class, needLogin = false)
	final public static int P_CCL_APPLICANT_COUNT_REQ = 0x8002c;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.ClCBanClubSYN.class, needLogin = false)
	final public static int P_CLC_BAN_CLUB_SYN = 0x8002d;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.club.ClubProtoBuf.ClCBeKickClubSYN.class, needLogin = false)
	final public static int P_CLC_BE_KICK_CLUB_SYN = 0x8002e;

	//Agent Protocols for Clients and server 0x0009xxxx, xxxx start from 0x0000
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.agent.AgentProtoBuf.CTHaveDiamondREQ.class, needLogin = false)
	final public static int P_CT_HAVE_DIAMOND_REQ = 0x90001;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.agent.AgentProtoBuf.TCHaveDiamondRES.class, needLogin = false)
	final public static int P_TC_HAVE_DIAMOND_RES = 0x90002;
		final public static int TC_HAVE_DIAMOND_RES_SUCCESS = 0x190002;
		final public static int TC_HAVE_DIAMOND_RES_AGENT_NOT_EXIST = 0x1090002;
		final public static int TC_HAVE_DIAMOND_RES_FAILED = 0x1190002;
		final public static int TC_HAVE_DIAMOND_RES_NOConnection = 0x1290002;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.agent.AgentProtoBuf.CTDiamondJournalREQ.class, needLogin = false)
	final public static int P_CT_DIAMOND_JOURNAL_REQ = 0x90003;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.agent.AgentProtoBuf.TCDiamondJournalRES.class, needLogin = false)
	final public static int P_TC_DIAMOND_JOURNAL_RES = 0x90004;
		final public static int TC_DIAMOND_JOURNAL_RES_SUCCESS = 0x190004;
		final public static int TC_DIAMOND_JOURNAL_RES_AGENT_NOT_EXIST = 0x1090004;
		final public static int TC_DIAMOND_JOURNAL_RES_FAILED = 0x1190004;
		final public static int TC_DIAMOND_JOURNAL_RES_NOConnection = 0x1290004;

	//Game Protocols for Agent and server 0x0010xxxx, xxxx start from 0x0000
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.agent.AgentProtoBuf.TGHaveDiamondREQ.class, needLogin = false)
	final public static int P_TG_HAVE_DIAMOND_REQ = 0x100001;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.agent.AgentProtoBuf.GTHaveDiamondRES.class, needLogin = false)
	final public static int P_GT_HAVE_DIAMOND_RES = 0x100002;
		final public static int GT_HAVE_DIAMOND_RES_SUCCESS = 0x200002;
		final public static int GT_HAVE_DIAMOND_RES_FAILED = 0x1100002;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.agent.AgentProtoBuf.TGDiamondJournalREQ.class, needLogin = false)
	final public static int P_TG_DIAMOND_JOURNAL_REQ = 0x100003;
	 @ProtocolConfigAnnotation(protocolClass = com.kodgames.message.proto.agent.AgentProtoBuf.GTDiamondJournalRES.class, needLogin = false)
	final public static int P_GT_DIAMOND_JOURNAL_RES = 0x100004;
		final public static int GT_DIAMOND_JOURNAL_RES_SUCCESS = 0x200004;
		final public static int GT_DIAMOND_JOURNAL_RES_FAILED = 0x1100004;

}
