module kodUtil {
	//This file is generated by program. No not edit it manually.
		export class PlatformErrorCode{
			public static codeMap:kodUtil.Map<number,string> = new kodUtil.HashMap<number,string>();

			//Client and Auth Protocols for Clients 0x0000xxxx, xxxx start from 0x0000
			


			//Auth Protocols for Interface 0x0001xxxx, xxxx start from 0x0000
			
			//账号认证
			public static P_IA_ACCOUNT_AUTH_REQ:number = 0x10001;
			//账号认证
			public static P_AI_ACCOUNT_AUTH_RES:number = 0x10002;
			//认证成功
			public static AI_AUTH_SUCCESS:number = 0x110002;
			//微信认证失败，请重新认证
			public static AI_AUTH_FAILED_INVALID_CHANNEL:number = 0x1010002;
			//微信认证失败，请重新认证
			public static AI_AUTH_FAILED_INVALID_USERNAME:number = 0x1110002;
			//微信认证失败，请重新认证
			public static AI_AUTH_FAILED_INVALID_ARGUMENTS:number = 0x1210002;
			//微信认证失败，请重新认证
			public static AI_AUTH_FAILED_WX_INVALID_CODE:number = 0x1310002;
			//微信认证失败，请重新认证
			public static AI_AUTH_FAILED_WX_INVALID_REFRESH_TOKEN:number = 0x1410002;
			//游戏版本需要更新
			public static AI_AUTH_FAILED_FORCE_UPDATE:number = 0x1510002;
			//微信认证失败，请重新认证
			public static AI_AUTH_FAILED_UNKNOWN:number = 0x1610002;
			//禁止注册
			public static AI_AUTH_FAILED_FORBID_REGISTER:number = 0x1710002;
			//无效的设备id
			public static AI_AUTH_FAILED_INVALID_DEVICEID:number = 0x1810002;
			//无效的appCode
			public static AI_AUTH_FAILED_INVALID_APPCODE:number = 0x1910002;
			//合并玩家信息请求
			public static P_AI_MERGE_PLAYER_INFO_REQ:number = 0x10003;
			//合并玩家信息回复
			public static P_IA_MERGE_PLAYER_INFO_RES:number = 0x10004;
			//合并玩家信息请求
			public static P_IG_MERGE_PLAYER_INFO_REQ:number = 0x10005;
			//合并玩家信息回复
			public static P_GI_MERGE_PLAYER_INFO_RES:number = 0x10006;
			//合并玩家信息成功
			public static GI_MERGE_PLAYER_INFO_SUCCESS:number = 0x1010006;
			//没有找到玩家信息
			public static GI_MERGE_PLAYER_INFO_FAIL_NO_PLAYER_INFO:number = 0x1110006;
			//更新信息请求
			public static P_IA_VERSION_UPDATE_REQ:number = 0x10007;
			//更新信息回复
			public static P_AI_VERSION_UPDATE_RES:number = 0x10008;
			//请求信息成功
			public static AI_VERSION_UPDATE_SUCCESS:number = 0x1010008;
			//渠道无效，登录失败
			public static AI_VERSION_UPDATE_FAIL_NO_CHANNEL_INFO:number = 0x1110008;
			//有新版本可用，请进行更新
			public static AI_VERSION_UPDATE_FAIL_FORCE_UPDATE:number = 0x1210008;
			//有新版本可用，是否进行更新
			public static AI_VERSION_UPDATE_FAIL_MANUAL_UPDATE:number = 0x1310008;
			//
			public static AI_VERSION_UPDATE_FAIL_REVIEW_VERSION:number = 0x1410008;


			//Interface Protocols for Clients and server 0x0002xxxx, xxxx start from 0x0000
			
			//账号认证
			public static P_CI_ACCOUNT_AUTH_REQ:number = 0x20001;
			//账号认证
			public static P_IC_ACCOUNT_AUTH_RES:number = 0x20002;
			//认证成功
			public static IC_AUTH_SUCCESS:number = 0x1020002;
			//认证失败，请重新认证
			public static IC_AUTH_FAILED_NO_AUTH_SERVER:number = 0x1120002;
			//更新信息请求
			public static P_CI_VERSION_UPDATE_REQ:number = 0x20003;
			//更新信息回复
			public static P_IC_VERSION_UPDATE_RES:number = 0x20004;


			//Client and Game Protocols for Clients 0x0003xxxx, xxxx start from 0x0000
			
			//账号登录
			public static P_CG_LOGIN_REQ:number = 0x30001;
			//账号登录
			public static P_GC_LOGIN_RES:number = 0x30002;
			//登录成功
			public static GC_LOGIN_SUCCESS:number = 0x130002;
			//登录失败，请重新登录
			public static GC_LOGIN_FAILED:number = 0x1030002;
			//登录失败，请重新登录
			public static GC_LOGIN_FAILED_INVALID_PARAM:number = 0x1130002;
			//登录失败，您已被封号
			public static GC_LOGIN_FAILED_FORBID_ROLE:number = 0x1230002;
			//登录失败，渠道无效
			public static GC_LOGIN_FAILED_INVALID_CHANNEL:number = 0x1330002;
			//无效的玩家信息
			public static GC_LOGIN_FAILED_INVALID_PLAYER_INFO:number = 0x1430002;
			//账号登出
			public static P_CG_LOGOUT_REQ:number = 0x30003;
			//账号登出
			public static P_GC_LOGOUT_RES:number = 0x30004;
			//登录成功
			public static GC_LOGOUT_SUCCESS:number = 0x130004;
			//登录失败，请重新登录
			public static GC_LOGOUT_FAILED:number = 0x1030004;
			//请求创建房间
			public static P_CG_CREATE_ROOM_REQ:number = 0x30005;
			//创建房间信息
			public static P_GC_CREATE_ROOM_RES:number = 0x30006;
			//创建房间成功
					
			public static GC_CREATE_ROOM_SUCCESS:number = 0x130006;
			//钻石不足
			public static GC_CREATE_ROOM_FAILED_ROOMCARD_NOT_ENOUGTH:number = 0x1030006;
			//
			public static GC_CREATE_ROOM_FAILED_NO_BATTLE:number = 0x1130006;
			//
			public static GC_CREATE_ROOM_FAILED_ALREADY_IN_ROOM:number = 0x1230006;
			//
			public static GC_CREATE_ROOM_FAILED_CREATING:number = 0x1330006;
			//
			public static GC_CREATE_ROOM_FAILED_INVALID_ROUND_COUNT:number = 0x1430006;
			//限免活动已结束
			public static GC_CREATE_ROOM_NO_LCA:number = 0x1530006;
			//请求战斗服信息
			public static P_CG_QUERY_BATTLEID_REQ:number = 0x30007;
			//战斗服信息
			public static P_GC_QUERY_BATTLEID_RES:number = 0x30008;
			//进入房间成功
					
			public static GC_QUERY_BATTLEID_SUCCESS:number = 0x130008;
			//房间不存在
			public static GC_QUERY_BATTLEID_FAILED_ROOM_NOT_EXIST:number = 0x1030008;
			//俱乐部房间，不能输入号码进入！
			public static GC_QUERY_BATTLEID_FAILED_CLUB_ROOM:number = 0x1130008;
			//钻石不足
			public static GC_QUERY_BATTLEID_FAILED_CARDCOUNT_NOT_ENOUGH:number = 0x1230008;
			//请求战绩
			public static P_CG_HISTORY_REQ:number = 0x30009;
			//战绩
			public static P_GC_HISTORY_RES:number = 0x3000a;
			//请求战绩成功
			public static GC_HISTORY_SUCCESS:number = 0x13000a;
			//
			public static GC_HISTORY_FAILED:number = 0x103000a;
			//请求详细战绩
			public static P_CG_HISTORY_ROOM_REQ:number = 0x3000b;
			//战绩详细
			public static P_GC_HISTORY_ROOM_RES:number = 0x3000c;
			//请求详细战绩成功
			public static GC_HISTORY_ROOM_SUCCESS:number = 0x13000c;
			//
			public static GC_HISTORY_ROOM_FAILED:number = 0x103000c;
			//房间战绩已经不存在
			public static GC_HISTORY_FAILED_ROOM_HISTORY_NOT_EXIST:number = 0x113000c;
			//通知client有新的mail
			public static P_GC_NEW_MAIL_SYNC:number = 0x3000d;
			//请求未读邮件列表
			public static P_CG_MAIL_REQ:number = 0x3000e;
			//邮件列表返回
			public static P_GC_MAIL_RES:number = 0x3000f;
			//同步立刻发送跑马灯当前版本
			public static P_GC_MARQUEE_VERSION_SYNC:number = 0x30010;
			//请求跑马灯列表
			public static P_CG_MARQUEE_REQ:number = 0x30011;
			//跑马灯列表返回
			public static P_GC_MARQUE_RES:number = 0x30012;
			//成功
			public static GC_MARQUEE_SUCCESS:number = 0x130012;
			//公告版本号同步消息
			public static P_GC_NOTICE_SYN:number = 0x30013;
			//公告请求消息
			public static P_CG_NOTICE_REQ:number = 0x30014;
			//公告应答消息
			public static P_GC_NOTICE_RES:number = 0x30015;
			//成功
			public static GC_NOTICE_SUCCESS:number = 0x130015;
			//请求联系代理商
			public static P_CG_CONTACT_REQ:number = 0x30016;
			//联系代理商返回
			public static P_GC_CONTACT_RES:number = 0x30017;
			//成功
			public static GC_CONTACT_SUCCESS:number = 0x130017;
			//扣卡通知
			public static P_GC_ROOMCARD_MODIFY_SYNC:number = 0x30018;
			//踢下线通知
			public static P_GC_KICKOFF_SYNC:number = 0x30019;
			//账号重复登录，您被踢下线
			public static GC_KICKOFF_SAME_LOGIN:number = 0x1030019;
			//防沉迷通知
			public static P_GC_ANTI_ADDICTION_SYN:number = 0x3001a;
			//请求邀请者的房间信息
			public static P_CG_INVITER_ROOMINFO_REQ:number = 0x3001b;
			//回复请求邀请者信息和房间信息
			public static P_GC_INVITER_ROOMINFO_RES:number = 0x3001c;
			//请求信息成功
			public static GC_INVITER_ROOMINFO_SUCCEE:number = 0x103001c;
			//请求的房间不存在
			public static GC_INVITER_ROOMINFO_FAILED_ROOM_NOT_EXIST:number = 0x113001c;
			//邀请者不存在
			public static GC_INVITER_ROOMINFO_FAILED_INVITER_NOT_EXIST:number = 0x123001c;
			//请求单日排名
			public static P_CG_ACTIVITY_RANK_REQ:number = 0x3001d;
			//应答单日排名
			public static P_GC_ACTIVITY_RANK_RES:number = 0x3001e;
			//请求信息成功
			public static GC_ACTIVITY_RANK_SUCCESS:number = 0x103001e;
			//活动不存在
			public static GC_ACTIVITY_FAILED_NOT_EXIST:number = 0x113001e;
			//活动未开始
			public static GC_ACTIVITY_FAILED_TOO_EARLY:number = 0x123001e;
			//活动已结束
			public static GC_ACTIVITY_FAILED_TOO_LATE:number = 0x133001e;
			//查询转盘信息
			public static P_CG_QUERY_TURNTABLE_INFO_REQ:number = 0x3001f;
			//回复查询转盘信息
			public static P_GC_QUERY_TURNTABLE_INFO_RES:number = 0x30020;
			//查询转盘信息成功
			public static GC_QUERY_TURNTABLE_INFO_SUCCESS:number = 0x1030020;
			//转盘抽奖
			public static P_CG_TURNTABLE_DRAW_REQ:number = 0x30021;
			//回复转盘抽奖
			public static P_GC_TURNTABLE_DRAW_RES:number = 0x30022;
			//转盘抽奖成功
			public static GC_TURNTABLE_DRAW_SUCCESS:number = 0x1030022;
			//抽奖次数不够
			public static GC_TURNTABLE_DRAW_NO_MORE_ITEM:number = 0x1130022;
			//转盘活动未在活动期间内
			public static GC_TURNTABLE_DRAW_INACTIVE:number = 0x1230022;
			//转盘奖励分享
			public static P_CG_SHARE_TURNTABLE_REWARD_REQ:number = 0x30023;
			//回复转盘奖励分享
			public static P_GC_SHARE_TURNTABLE_REWARD_RES:number = 0x30024;
			//
			public static GC_SHARE_TURNTABLE_REWARD_SUCCESS:number = 0x1030024;
			//玩家有抽奖机会
			public static P_GC_PLAYER_HAS_ITEM_COUNT_SYN:number = 0x30025;
			//限免活动同步消息
			public static P_GC_NEW_LIMITED_COSTLESS_ACTIVITY_SYN:number = 0x30026;
			//限免活动请求消息
			public static P_CG_LIMITED_COSTLESS_ACTIVITY_REQ:number = 0x30027;
			//限免活动应答消息
			public static P_GC_LIMITED_COSTLESS_ACTIVITY_RES:number = 0x30028;
			//成功
			public static GC_LIMITED_COSTLESS_ACTIVITY_SUCCESS:number = 0x130028;
			//时间同步请求消息
			public static P_GC_TIME_SYNCHRONIZATION_REQ:number = 0x30029;
			//时间同步应答消息
			public static P_GC_TIME_SYNCHRONIZATION_RES:number = 0x3002a;
			//成功
			public static GC_TIME_SYNCHRONIZATION_SUCCESS:number = 0x13002a;
			//常驻公告回复消息
			public static P_GC_MAIN_NOTICE_RES:number = 0x3002b;
			//成功
			public static GC_MAIN_NOTICE_SUCCESS:number = 0x13002b;
			//常驻公告请求消息
			public static P_CG_MAIN_NOTICE_REQ:number = 0x3002c;
			//推广代理员 客户端向服务器发送手机号
			public static P_CG_SNED_PHONE_NUMBER_REQ:number = 0x3002d;
			//服务器回应结果
			public static P_CG_SNED_PHONE_NUMBER_RES:number = 0x3002e;
			//签名验证错误
			public static GC_ERROR_SIGN_PN:number = 0x103002e;
			//该手机号已申请过推广员
			public static GC_AGENT_EXIST_PN:number = 0x113002e;
			//该手机号正在申请成为推广员，请联系客服进行进一步操作
			public static GC_AGENT_TEMP_PN:number = 0x123002e;
			//验证码发送失败，请确认手机号为有效的手机号
			public static GC_ERROR_PHONE_PN:number = 0x133002e;
			//发送成功
			public static GC_PHOHE_NUMBER_SUCCESS_PN:number = 0x13002e;
			//您已提交过申请！请勿重复申请
			public static GC_PHONE_NUMBER_PLAYER_EXIST_PN:number = 0x143002e;
			//是否已绑定手机请求消息
			public static P_CG_BIND_MOBILE_REQ:number = 0x3002f;
			//是否已绑定手机回复消息
			public static P_GC_BIND_MOBILE_RES:number = 0x30030;
			//未绑定手机
			public static GC_BIND_MOBILE_NO:number = 0x1030030;
			//已绑定手机
			public static GC_BIND_MOBILE_YES:number = 0x1130030;
			//验证码请求消息
			public static P_CG_SEND_BIND_CODE_REQ:number = 0x30031;
			//验证码回复消息
			public static P_GC_SEND_BIND_CODE_RES:number = 0x30032;
			//获取验证码成功
			public static GC_SEND_BIND_CODE_SUCCESS:number = 0x1030032;
			//获取验证码失败
			public static GC_SEND_BIND_CODE_FAIL:number = 0x1130032;
			//获取失败，每30秒可获取一次
			public static GC_SEND_BIND_CODE_LIMIT:number = 0x1230032;
			//已绑定，不可再次绑定
			public static GC_SEND_BIND_CODE_BIND_BEFORE:number = 0x1330032;
			//绑定手机验证码请求消息
			public static P_CG_BIND_VAILD_REQ:number = 0x30033;
			//绑定手机绑定手机验证码回复消息
			public static P_GC_BIND_VAILD_RES:number = 0x30034;
			//已绑定，验证码正确
			public static GC_BIND_VAILD_OK:number = 0x1030034;
			//验证码错误
			public static GC_BIND_VAILD_ERROR:number = 0x1130034;
			//验证码过期
			public static GC_BIND_VAILD_OVERTIME:number = 0x1230034;
			//未获取验证码
			public static GC_NOT_GET_CODE:number = 0x1330034;
			//推广代理员 客户端向服务器发送验证码和手机号
			public static P_CG_SNED_VERIFICATION_CODE_REQ:number = 0x30035;
			//服务器回应结果
			public static P_CG_SNED_VERIFICATION_CODE_RES:number = 0x30036;
			//签名验证错误
			public static GC_ERROR_SIGN_VC:number = 0x1030036;
			//该手机号已申请过推广员
			public static GC_AGENT_EXIST_VC:number = 0x1130036;
			//该手机号正在申请成为推广员，请联系客服进行进一步操作
			public static GC_AGENT_TEMP_VC:number = 0x1230036;
			//验证码发送失败，请确认手机号为有效的手机号
			public static GC_ERROR_PHONE_VC:number = 0x1330036;
			//验证码发送失效
			public static GC_EXRIPE_VERIYCODE_VC:number = 0x1430036;
			//验证码错误
			public static GC_ERROR_VERIFYCODE_VC:number = 0x1530036;
			//发送成功
			public static GC_PHOHE_NUMBER_SUCCESS_VC:number = 0x130036;
			//查询推广员奖励信息
			public static P_CG_QUERY_PROMOTER_REWARDS_REQ:number = 0x30037;
			//查询推广员奖励信息回复
			public static P_GC_QUERY_PROMOTER_REWARD_RES:number = 0x30038;
			//成功
			public static GC_QUERY_PROMOTER_REWARD_SUCCESS:number = 0x130038;
			//不在活动期间
			public static GC_QUERY_PROMOTER_REWARD_FAILED_ACTIVITY_INACTIVE:number = 0x1030038;
			//无法查询奖励信息
			public static GC_QUERY_PROMOTER_REWARD_FAILED_PROMOTER_ABSENT:number = 0x1130038;
			//推广员领取奖励请求
			public static P_CG_PROMOTER_REWARD_REQ:number = 0x30039;
			//推广员领取奖励回复
			public static P_GC_PROMOTER_REWARD_RES:number = 0x3003a;
			//成功
			public static GC_PROMOTER_REWARD_SUCCESS:number = 0x13003a;
			//不在活动期间
			public static GC_PROMOTER_REWARD_FAILED_ACTIVITY_INACTIVE:number = 0x103003a;
			//领奖失败，未知原因
			public static GC_PROMOTER_REWARD_FAILED:number = 0x113003a;
			//推广员分享请求
			public static P_CG_PROMOTER_SHARE_REQ:number = 0x3003b;
			//推广员分享回复
			public static P_GC_PROMOTER_SHARE_RES:number = 0x3003c;
			//成功
			public static GC_PROMOTER_SHARE_SUCCESS:number = 0x13003c;
			//分享失败
			public static GC_PROMOTER_SHARE_FAILED:number = 0x103003c;
			//弹窗消息请求
			public static P_CG_POP_UP_MESSAGE_INFO_REQ:number = 0x3003d;
			//弹窗消息回复
			public static P_CG_POP_UP_MESSAGE_INFO_RES:number = 0x3003e;
			//成功
			public static GC_POP_UP_MESSAGE_INFO_RES_SUCCESS:number = 0x13003e;
			//没有新的弹窗消息
			public static GC_POP_UP_MESSAGE_INFO_RES_VERSION_SAME:number = 0x103003e;
			//没有弹窗消息
			public static GC_POP_UP_MESSAGE_INFO_RES_FAILED_MESSAGE_IS_ABSENT:number = 0x113003e;
			//通知client有新的弹窗消息
			public static P_GC_POP_UP_MESSAGE_INFO_SYNC:number = 0x3003f;
			//请求创建房间
			public static P_CG_CONTINUE_ROOM_REQ:number = 0x30040;
			//创建房间信息
			public static P_GC_CONTINUE_ROOM_RES:number = 0x30041;
			//恭喜您续房成功并成为房主！
					
			public static GC_CONTINUE_ROOM_SUCCESS:number = 0x130041;
			//您的钻石不足，续房失败！
			public static GC_CONTINUE_ROOM_FAILED_ROOMCARD_NOT_ENOUGTH:number = 0x1030041;
			//
			public static GC_CONTINUE_ROOM_FAILED_NO_BATTLE:number = 0x1130041;
			//
			public static GC_CONTINUE_ROOM_FAILED_ALREADY_IN_ROOM:number = 0x1230041;
			//
			public static GC_CONTINUE_ROOM_FAILED_CREATING:number = 0x1330041;
			//
			public static GC_CONTINUE_ROOM_FAILED_INVALID_ROUND_COUNT:number = 0x1430041;
			//续房超时，无法再战
			public static GC_CONTINUE_ROOM_FAILED_NO_OLD_ROOM:number = 0x1530041;
			//限免活动已结束
			public static GC_CONTINUE_ROOM_NO_LCA:number = 0x1630041;
			//请求继续加入房间
			public static P_CG_CONTINUE_ENTER_ROOM_REQ:number = 0x30042;
			//请求继续加入信息
			public static P_GC_CONTINUE_ENTER_ROOM_RES:number = 0x30043;
			//续房成功
					
			public static GC_CONTINUE_ENTER_ROOM_SUCCESS:number = 0x130043;
			//您的钻石不足，续房失败！
			public static GC_CONTINUE_ENTER_ROOM_FAILED_ROOMCARD_NOT_ENOUGTH:number = 0x1030043;
			//俱乐部房间，不能输入号码进入！
			public static GC_CONTINUE_ENTER_ROOM_FAILED_CLUB_ROOM:number = 0x1130043;
			//该房间已解散，再战失败！
			public static GC_CONTINUE_ENTER_ROOM_FAILED_ROOM_NOT_EXIST:number = 0x1230043;
			//该房间人数已满，去重新创建房间吧！
			public static GC_CONTINUE_ENTER_ROOM_FAILED_ROOM_FULL:number = 0x1330043;
			//续房超时，无法再战
			public static GC_CONTINUE_ENTER_ROOM_FAILED_NO_OLD_ROOM:number = 0x1430043;
			//
			public static GC_CONTINUE_ENTER_ROOM_CONNECTION_ERROR:number = 0x1530043;


			//Client and Battle Protocols for Clients 0x0004xxxx, xxxx start from 0x0000
			
			//进入房间
			public static P_CB_ENTER_ROOM_REQ:number = 0x40001;
			//进入房间
			public static P_BC_ENTER_ROOM_RES:number = 0x40002;
			//进入房间成功
			public static BC_ENTER_ROOM_SUCCESS:number = 0x140002;
			//
			public static BC_ENTER_ROOM_FAILED:number = 0x1040002;
			//房间不存在
			public static BC_ENTER_ROOM_FAILED_ROOM_NOT_EXIST:number = 0x1140002;
			//房间人数已满
			public static BC_ENTER_ROOM_FAILED_ROOM_FULL:number = 0x1240002;
			//
			public static BC_ENTER_ROOM_FAILED_MEMBERS_ERROR:number = 0x1340002;
			//房间玩家信息同步
			public static P_BC_ROOM_PLAYERINFO_SYN:number = 0x40003;
			//玩家主动退出房间
			public static P_CB_QUIT_ROOM_REQ:number = 0x40004;
			//玩家主动退出房间
			public static P_BC_QUIT_ROOM_RES:number = 0x40005;
			//退出成功
			public static BC_QUIT_ROOM_SUCCESS:number = 0x140005;
			//
			public static BC_QUIT_ROOM_FAILED:number = 0x1040005;
			//
			public static BC_QUIT_ROOM_FAILED_NOT_IN_ROOM:number = 0x1140005;
			//
			public static BC_QUIT_ROOM_FAILED_IN_BATTLE:number = 0x1240005;
			//申请发起投票
			public static P_CB_START_VOTE_DESTROY_REQ:number = 0x40006;
			//申请发起投票
			public static P_BC_START_VOTE_DESTROY_RES:number = 0x40007;
			//发起投票成功
			public static BC_START_VOTE_SUCCESS:number = 0x140007;
			//
			public static BC_START_VOTE_FAILED_NOT_IN_ROOM:number = 0x1040007;
			//
			public static BC_START_VOTE_FAILED_WITHOUT_BATTLE:number = 0x1140007;
			//
			public static BC_START_VOTE_FAILED_VOTING:number = 0x1240007;
			//申请解散房间或投票
			public static P_CB_VOTE_DESTROY_REQ:number = 0x40008;
			//申请解散房间或投票结果
			public static P_BC_VOTE_DESTROY_RES:number = 0x40009;
			//投票成功
			public static BC_VOTE_DESTROY_SUCCESS:number = 0x140009;
			//投票失败，您没有在房间中
			public static BC_VOTE_DESTROY_FAILED_NOT_IN_ROOM:number = 0x1040009;
			//投票失败，您已经投过票
			public static BC_VOTE_DESTROY_FAILED_HAS_VOTED:number = 0x1140009;
			//投票失败，牌局还未开始
			public static BC_VOTE_DESTROY_FAILED_WITHOUT_BATTLE:number = 0x1240009;
			//投票失败，没有发起投票
			public static BC_VOTE_DESTROY_FAILED_WITHOUT_VOTE:number = 0x1340009;
			//房间玩家信息同步
			public static P_BC_VOTE_DESTROYINFO_SYN:number = 0x4000a;
			//房间玩家信息同步
			public static P_BC_DESTROY_ROOM_SYN:number = 0x4000b;
			//投票解散
			public static BC_DESTROY_ROOM_VOTE:number = 0x14000b;
			//GMT强制解散
			public static BC_DESTROY_ROOM_GMT:number = 0x24000b;
			//更新玩家状态
			public static P_CB_UPDATE_PLAYERSTATUS_REQ:number = 0x4000c;
			//更新玩家状态
			public static P_BC_UPDATE_PLAYERSTATUS_RES:number = 0x4000d;
			//更新成功
			public static BC_UPDATE_PLAYERSTATUS_SUCCESS:number = 0x14000d;
			//
			public static BC_UPDATE_PLAYERSTATUS_FAILED_NOT_IN_ROOM:number = 0x104000d;
			//
			public static BC_UPDATE_PLAYERSTATUS_FAILED_INVALID_STATUS:number = 0x114000d;
			//房间牌局信息同步
			public static P_BC_BATTLE_PLAYERINFO_SYN:number = 0x4000e;
			//房间出牌信息同步
			public static P_BC_PLAYSTEP_SYN:number = 0x4000f;
			//操作
			public static P_CB_PLAYCARD_REQ:number = 0x40010;
			//操作结果
			public static P_BC_PLAYCARD_RES:number = 0x40011;
			//出牌成功
			public static BC_PLAYCARD_SUCCESS:number = 0x140011;
			//
			public static BC_PLAYCARD_FAILED_NOT_IN_ROOM:number = 0x1040011;
			//
			public static BC_PLAYCARD_FAILED_NOT_HAVE_THIS_CARD:number = 0x1140011;
			//
			public static BC_PLAYCARD_FAILED_NOT_MATCH_THIS_CARD:number = 0x1240011;
			//
			public static BC_PLAYCARD_FAILED_NOT_YOUR_TURN:number = 0x1340011;
			//
			public static BC_PLAYCARD_FAILED_NOT_VALID_ROLEID:number = 0x1440011;
			//房间单局信息同步
			public static P_BC_MATCHRESULT_SYN:number = 0x40012;
			//房间总局信息同步
			public static P_BC_FINALMATCHRESULT_SYN:number = 0x40013;
			//请求聊天
			public static P_CB_CHAT_REQ:number = 0x40014;
			//响应聊天
			public static P_BC_CHAT_RES:number = 0x40015;
			//聊天成功
			public static BC_CHAT_SUCCESS:number = 0x140015;
			//
			public static BC_CHAT_FAILED_NOT_IN_ROOM:number = 0x1040015;
			//同步聊天
			public static P_BC_CHAT_SYN:number = 0x40016;
			//同IP提示
			public static P_BC_SAME_IP_SYN:number = 0x40017;
			//请求播放动画
			public static P_CB_ANIMATION_REQ:number = 0x40018;
			//响应播放动画
			public static P_BC_ANIMATION_RES:number = 0x40019;
			//播放成功
			public static BC_ANIMATION_SUCCESS:number = 0x140019;
			//
			public static BC_ANIMATION_FAILED_NOT_IN_ROOM:number = 0x1040019;
			//同步播放动画
			public static P_BC_ANIMATION_SYN:number = 0x4001a;
			//gps同步请求
			public static P_CB_GPS_INFO_REQ:number = 0x4001b;
			//gps同步响应
			public static P_BC_GPS_INFO_RES:number = 0x4001c;
			//同步成功
			public static BC_GPS_INFO_SUCCESS:number = 0x14001c;
			//同步失败
			public static BC_GPS_INFO_FAILED_NOT_IN_ROOM:number = 0x104001c;
			//gps信息推送
			public static P_BC_SECUREDETECTSYN_RES:number = 0x4001d;
			//同步续房信息
			public static P_BC_IS_CONTINUE_ROOM_SYN:number = 0x4001e;
			//同步进入续房信息
			public static P_BC_CONTINUE_ROOM_PLAYER_INFO_SYN:number = 0x4001f;


			//Game and Battle Protocols for Clients 0x0005xxxx, xxxx start from 0x0000
			
			//请求创建房间
			public static P_GB_CREATE_ROOM_REQ:number = 0x50001;
			//创建房间应答
			public static P_BG_CREATE_ROOM_RES:number = 0x50002;
			//成功
			public static BG_CREATE_ROOM_SUCCESS:number = 0x150002;
			//
			public static BG_CREATE_ROOM_FAILED:number = 0x1050002;
			//
			public static BG_CREATE_ROOM_FAILED_ROOM_EXIST:number = 0x1150002;
			//
			public static BG_CREATE_ROOM_FAILED_INVALID_GAMEPLAYS:number = 0x1250002;
			//
			public static BG_CREATE_ROOM_FAILED_INVALID_ROUNDCOUNT:number = 0x1350002;
			//进入房间信息同步
			public static P_BG_ENTER_ROOM_SYN:number = 0x50003;
			//退出房间信息同步
			public static P_BG_QUIT_ROOM_SYN:number = 0x50004;
			//销毁房间信息同步
			public static P_BG_DESTROY_ROOM_SYN:number = 0x50005;
			//扣卡信息同步
			public static P_BG_ROOMCARD_MODIFY_SYN:number = 0x50006;
			//房间结算
			public static P_BG_MATCH_RESULT_SYN:number = 0x50007;
			//房间状态
			public static P_BG_ROOM_STATUS_SYN:number = 0x50008;
			//房间状态
			public static P_BG_RECORD_LOG_SYN:number = 0x50009;
			//强制解散房间
			public static P_GB_FORCE_DESTROY_ROOM_SYN:number = 0x5000a;
			//同步游戏配置
			public static P_GB_GAME_CONFIG_SYN:number = 0x5000b;
			//同步游戏配置
			public static P_GCL_GAME_CONFIG_SYN:number = 0x5000c;
			//请求邀请者的房间信息
			public static P_GB_INVITER_ROOMINFO_REQ:number = 0x5000d;
			//回复请求邀请者信息和房间信息
			public static P_BG_INVITER_ROOMINFO_RES:number = 0x5000e;
			//请求信息成功
			public static BG_INVITER_ROOMINFO_SUCCEE:number = 0x105000e;
			//请求的房间不存在
			public static BG_INVITER_ROOMINFO_FAILED_ROOM_NOT_EXIST:number = 0x115000e;
			//邀请者不存在
			public static BG_INVITER_ROOMINFO_FAILED_INVITER_NOT_EXIST:number = 0x125000e;
			//总房间结算
			public static P_BG_FINAL_MATCH_RESULT_SYN:number = 0x5000f;
			//Club向Game请求玩家的游戏局数
			public static P_CG_JOIN_ROLEINFO_REQ:number = 0x50010;
			//返回玩家的游戏局数
			public static P_GC_JOIN_ROLEINFO_RES:number = 0x50011;
			//请求信息成功
			public static GC_JOIN_ROLEINFO_SUCCEE:number = 0x1050011;
			//请求的玩家不存在
			public static GC_JOIN_ROLEINFO_ROLE_NOT_FOUND:number = 0x1150011;
			//请求创建房间
			public static P_GB_CONTINUE_ROOM_REQ:number = 0x50012;
			//创建房间应答
			public static P_BG_CONTINUE_ROOM_RES:number = 0x50013;
			//成功
			public static BG_CONTINUE_ROOM_SUCCESS:number = 0x150013;
			//
			public static BG_CONTINUE_ROOM_FAILED:number = 0x1050013;
			//
			public static BG_CONTINUE_ROOM_FAILED_ROOM_EXIST:number = 0x1150013;
			//
			public static BG_CONTINUE_ROOM_FAILED_INVALID_GAMEPLAYS:number = 0x1250013;
			//
			public static BG_CONTINUE_ROOM_FAILED_INVALID_ROUNDCOUNT:number = 0x1350013;
			//请求继续加入房间
			public static P_GB_CONTINUE_ENTER_ROOM_REQ:number = 0x50014;
			//请求继续加入信息
			public static P_BG_CONTINUE_ENTER_ROOM_RES:number = 0x50015;
			//进入房间成功
			public static BG_CONTINUE_ENTER_ROOM_SUCCESS:number = 0x150015;
			//房间不存在
			public static BG_CONTINUE_ENTER_ROOM_FAILED_ROOM_NOT_EXIST:number = 0x1050015;
			//房间人数已满
			public static BG_CONTINUE_ENTER_ROOM_FAILED_ROOM_FULL:number = 0x1150015;
			//
			public static BG_CONTINUE_ENTER_ROOM_CONNECTION_ERROR:number = 0x1250015;
			//同步给Battle玩家已经进入房间
			public static P_BG_CONTINUE_ENTER_ROOM_OVER_SYN:number = 0x50016;
			//请求战绩
			public static P_CG_HISTORY_PLAYBACK_REQ:number = 0x50017;
			//战绩
			public static P_GC_HISTORY_PLAYBACK_RES:number = 0x50018;
			//请求战绩成功
			public static GC_HISTORY_PLAYBACK_SUCCESS:number = 0x150018;
			//
			public static GC_HISTORY_PLAYBACK_FAILED:number = 0x1050018;


			//Protocols for Servers 0x0006xxxx, xxxx start from 0x0000
			//请求启动配置信息
			public static P_SS_GET_LAUNCH_INFO_REQ:number = 0x60001;
			//启动配置信息返回
			public static P_SS_GETLAUNCH_INFO_RES:number = 0x60002;
			//成功
					
			public static SS_GET_LAUNCH_INFO_SUCCESS:number = 0x160002;
			//
			public static SS_GET_LAUNCH_INFO_FAILED:number = 0x1060002;
			//注册一个启动完成的server
			public static P_SS_REGISTER_SERVER_REQ:number = 0x60003;
			//同步一个在线的服务器列表或者一个上线的服务器
			public static P_SS_SERVER_LIST_SYNC:number = 0x60004;
			//同步一个下线的服务器
			public static P_SS_SERVER_DISCONNECT_SYNC:number = 0x60005;
			//客户端断开通知
			public static P_CLIENT_DISCONNECT_SYN:number = 0x60006;
			//交换服务器ID
			public static P_SS_EXCHANGE_PEER_INFO_SYN:number = 0x60007;
			//充值请求
			public static P_PLATFORM_PURCHASE_REQ:number = 0x60008;
			//充值返回
			public static P_PLATFORM_PURCHASE_RES:number = 0x60009;
			//成功
			public static SS_PLATFORM_PURCHASE_SUCCESS:number = 0x160009;
			//
			public static SS_PLATFORM_PURCHASE_FAILED:number = 0x1060009;
			//代理商充值请求
			public static P_PLATFORM_AGENT_PURCHASE_REQ:number = 0x6000a;
			//代理商充值返回
			public static P_PLATFORM_AGENT_PURCHASE_RES:number = 0x6000b;
			//成功
			public static SS_PLATFORM_AGENT_PURCHASE_SUCCESS:number = 0x16000b;
			//
			public static SS_PLATFORM_AGENT_PURCHASE_FAILED:number = 0x106000b;


			//Protocols for Clients 0x0007xxxx, xxxx start from 0x0000
			//服务器发生异常
			public static P_SERVER_EXCEPTION_SYNC:number = 0x70001;


			//Club Protocols for Clients and server 0x0008xxxx, xxxx start from 0x0000
			
			//创建俱乐部房间
			public static P_CCL_CREATE_ROOM_REQ:number = 0x80001;
			//创建俱乐部房间
			public static P_CLC_CREATE_ROOM_RES:number = 0x80002;
			//创建成功
			public static CLC_CREATE_ROOM_SUCCESS:number = 0x1080002;
			//没这个俱乐部
			public static CLC_CREATE_ROOM_FAILED_NO_SUCH_CLUB:number = 0x1180002;
			//没权限
			public static CLC_CREATE_ROOM_FAILED_NO_RIGHT:number = 0x1280002;
			//俱乐部房卡不够
			public static CLC_CREATE_ROOM_FAILED_NOT_ENOUGH_CARDS:number = 0x1380002;
			//经理俱乐部房卡不够
			public static CLC_CREATE_ROOM_FAILED_MANAGER_NOT_ENOUGH_CARDS:number = 0x1480002;
			//俱乐部被封停
			public static CLC_CREATE_ROOM_FAILED_CLUB_SEALED:number = 0x1580002;
			//创建俱乐部房间
			public static P_CLG_CREATE_ROOM_REQ:number = 0x80003;
			//创建俱乐部房间
			public static P_GCL_CREATE_ROOM_REQ:number = 0x80004;
			//创建成功
			public static GCL_CREATE_ROOM_SUCCESS:number = 0x1080004;
			//
			public static GCL_CREATE_ROOM_FAILED_ROOM_EXIST:number = 0x1180004;
			//
			public static GCL_CREATE_ROOM_FAILED_CREATING:number = 0x1280004;
			//
			public static GCL_CREATE_ROOM_FAILED_ALREADY_IN_ROOM:number = 0x1380004;
			//
			public static GCL_CREATE_ROOM_FAILED_NO_BATTLE:number = 0x1480004;
			//进入俱乐部房间
			public static P_CCL_ENTER_ROOM_REQ:number = 0x80005;
			//进入俱乐部房间
			public static P_CLC_ENTER_ROOM_RES:number = 0x80006;
			//创建成功
			public static CLC_ENTER_ROOM_SUCCESS:number = 0x1080006;
			//没这个房间
			public static CLC_ENTER_ROOM_FAILED_NO_SUCH_ROOM:number = 0x1180006;
			//玩家不在这个俱乐部里
			public static CLC_ENTER_ROOM_NOT_IN_CLUB:number = 0x1280006;
			//没权限
			public static CLC_ENTER_ROOM_FAILED_NO_RIGHT:number = 0x1380006;
			//俱乐部房卡不够
			public static CLC_ENTER_ROOM_FAILED_NOT_ENOUGH_CARDS:number = 0x1480006;
			//俱乐部被封停
			public static CLC_ENTER_ROOM_FAILED_CLUB_SEALED:number = 0x1580006;
			//同步进入俱乐部房间
			public static P_GCL_ENTER_ROOM_SYN:number = 0x80007;
			//同步离开俱乐部房间
			public static P_GCL_QUIT_ROOM_SYN:number = 0x80008;
			//同步销毁俱乐部房间
			public static P_GCL_DESTROY_ROOM_SYN:number = 0x80009;
			//同步GMT销毁俱乐部房间
			public static P_GCL_GMT_DESTROY_ROOM_SYN:number = 0x8000a;
			//同步俱乐部房卡数的变化
			public static P_CCL_CLUB_ROOM_CARD_MODIFY_SYN:number = 0x8000b;
			//同步这个房间可以扣卡了
			public static P_GCL_ENABLE_SUB_CARD_SYN:number = 0x8000c;
			//同步一局结算数据
			public static P_GCL_MATCH_RESULT_SYN:number = 0x8000d;
			//同步房间结算数据
			public static P_GCL_FINAL_MATCH_RESULT_SYN:number = 0x8000e;
			//请求俱乐部信息
			public static P_CCL_CLUB_INFO_REQ:number = 0x8000f;
			//返回俱乐部数据
			public static P_CLC_CLUB_INFO_RES:number = 0x80010;
			//请求成功
			public static CLC_CLUB_INFO_SUCCESS:number = 0x180010;
			//俱乐部不存在
			public static CLC_CLUB_NOT_FOUND:number = 0x1080010;
			//俱乐部封停
			public static CLC_CLUB_SEALED:number = 0x1180010;
			//邀请码错误
			public static CLC_CLUB_WRONG_CODE:number = 0x1280010;
			//已被踢出该俱乐部
			public static CLC_CLUB_KICK_OUT:number = 0x1380010;
			//通过邀请码请求俱乐部信息
			public static P_CCL_JOIN_CLUB_INFO_REQ:number = 0x80011;
			//返回邀请码对应的俱乐部数据
			public static P_CLC_JOIN_CLUB_INFO_RES:number = 0x80012;
			//请求加入俱乐部
			public static P_CCL_CLUB_JOIN_REQ:number = 0x80013;
			//返回请求加入俱乐部
			public static P_CLC_CLUB_JOIN_RES:number = 0x80014;
			//请求成功
			public static CLC_CLUB_JOIN_SUCCESS:number = 0x180014;
			//已经加入俱乐部
			public static CLC_CLUB_JOIN_ALREADY_JOINED:number = 0x1080014;
			//已经在申请列表中
			public static CLC_CLUB_JOIN_ALREADY_JOINED_APPLICANT:number = 0x1180014;
			//邀请人没有权限
			public static CLC_CLUB_JOIN_NOT_PERMITTED:number = 0x1280014;
			//请求退出俱乐部
			public static P_CCL_CLUB_QUIT_REQ:number = 0x80015;
			//返回退出加入俱乐部
			public static P_CLC_CLUB_QUIT_RES:number = 0x80016;
			//请求成功
			public static CLC_CLUB_QUIT_SUCCESS:number = 0x180016;
			//不是俱乐部成员
			public static CLC_CLUB_QUIT_NOT_IN_CLUB:number = 0x1080016;
			//请求俱乐部成员列表
			public static P_CCL_CLUB_MEMBERS_REQ:number = 0x80017;
			//返回俱乐部成员列表
			public static P_CLC_CLUB_MEMBERS_RES:number = 0x80018;
			//请求成功
			public static CLC_CLUB_MEMBERS_SUCCESS:number = 0x180018;
			//请求修改俱乐部公告
			public static P_CCL_CLUB_NOTICEMODIFY_REQ:number = 0x80019;
			//返回俱乐部公告修改结果
			public static P_CLC_CLUB_NOTICEMODIFY_RES:number = 0x8001a;
			//修改成功
			public static CLC_CLUB_NOTICEMODIFY_SUCCESS:number = 0x18001a;
			//修改失败, 俱乐部不存在
			public static CLC_CLUB_NOTICEMODIFY_CLUB_NOT_FOUND:number = 0x108001a;
			//修改失败, 没有权限
			public static CLC_CLUB_NOTICEMODIFY_NOT_PERMITED:number = 0x118001a;
			//修改失败, 字数超过限制
			public static CLC_CLUB_NOTICEMODIFY_TEXT_TOO_LONG:number = 0x128001a;
			//请求修改俱乐部消耗
			public static P_CCL_CLUB_COSTMODIFY_REQ:number = 0x8001b;
			//返回俱乐部消耗修改结果
			public static P_CLC_CLUB_COSTMODIFY_RES:number = 0x8001c;
			//修改成功
			public static CLC_CLUB_COSTMODIFY_SUCCESS:number = 0x18001c;
			//修改失败, 俱乐部不存在
			public static CLC_CLUB_COSTMODIFY_CLUB_NOT_FOUND:number = 0x108001c;
			//修改失败, 没有权限
			public static CLC_CLUB_COSTMODIFY_NOT_PERMITED:number = 0x118001c;
			//修改失败，最大可设置倍数是10
			public static CLC_CLUB_COSTMODIFY_ARGS_ERROR:number = 0x128001c;
			//请求修改会员参数
			public static P_CCL_CLUB_MEMBERMODIFY_REQ:number = 0x8001d;
			//返回会员参数修改结果
			public static P_CLC_CLUB_MEMBERMODIFY_RES:number = 0x8001e;
			//修改成功
			public static CLC_CLUB_MEMBERMODIFY_SUCCESS:number = 0x18001e;
			//修改失败, 没有权限
			public static CLC_CLUB_MEMBERMODIFY_NOT_PERMITED:number = 0x108001e;
			//请求俱乐部申请列表
			public static P_CCL_CLUB_APPLICANTS_REQ:number = 0x8001f;
			//返回俱乐部申请列表
			public static P_CLC_CLUB_APPLICANTS_RES:number = 0x80020;
			//获取成功
			public static CLC_CLUB_APPLICANTS_SUCCESS:number = 0x180020;
			//获取失败, 俱乐部不存在
			public static CLC_CLUB_APPLICANTS_CLUB_NOT_FOUND:number = 0x1080020;
			//获取失败, 没有权限
			public static CLC_CLUB_APPLICANTS_NOT_PERMITED:number = 0x1180020;
			//同意/拒绝申请
			public static P_CCL_CLUB_APPLICANT_REQ:number = 0x80021;
			//同意/拒绝申请的结果
			public static P_CLC_CLUB_APPLICANT_RES:number = 0x80022;
			//成功
			public static CLC_CLUB_APPLICANT_SUCCESS:number = 0x180022;
			//失败, 俱乐部不存在
			public static CLC_CLUB_APPLICANT_CLUB_NOT_FOUND:number = 0x1080022;
			//失败, 没有权限
			public static CLC_CLUB_APPLICANT_NOT_PERMITED:number = 0x1180022;
			//失败, 申请人不在列表中
			public static CLC_CLUB_APPLICANT_NOT_IN_LIST:number = 0x1280022;
			//失败, 申请人超过了可加入俱乐部的最大限制
			public static CLC_CLUB_APPLICANT_MAX_CLUBS:number = 0x1380022;
			//失败, 俱乐部人数限制
			public static CLC_CLUB_APPLICANT_MAX_MEMBERS:number = 0x1480022;
			//请求我所有的俱乐部
			public static P_CCL_ALL_CLUB_REQ:number = 0x80023;
			//返回我所有的俱乐部
			public static P_CLC_ALL_CLUB_RES:number = 0x80024;
			//请求成功
			public static CLC_ALL_CLUB_SUCCESS:number = 0x180024;
			//不在任何俱乐部中
			public static CLC_ALL_CLUB_NOT_IN_ANY_CLUB:number = 0x1080024;
			//请求我所有的俱乐部牌桌
			public static P_CCL_CLUB_TABLE_REQ:number = 0x80025;
			//返回我所有的俱乐部牌桌
			public static P_CLC_CLUB_TABLE_RES:number = 0x80026;
			//请求成功
			public static CLC_CLUB_TABLE_SUCCESS:number = 0x180026;
			//不在任何俱乐部中
			public static CLC_CLUB_TABLE_NOT_IN_ANY_CLUB:number = 0x1080026;
			//不在这个俱乐部中
			public static CLC_CLUB_TABLE_NOT_IN_THIS_CLUB:number = 0x1180026;
			//没有任何俱乐部牌桌
			public static CLC_CLUB_TABLE_ROOMS_NOT_FOUND:number = 0x1280026;
			//请求我所有的俱乐部牌桌
			public static P_CLG_CHECK_ROLE_INFO_REQ:number = 0x80027;
			//返回我所有的俱乐部牌桌
			public static P_GCL_CHECK_ROLE_INFO_RES:number = 0x80028;
			//请求成功
			public static GCL_CHECK_ROLE_INFO_SUCCESS:number = 0x180028;
			//没有任何俱乐部牌桌
			public static GCL_CHECK_ROLE_INFO_ROLE_NOT_FOUND:number = 0x1080028;
			//同步登陆数据
			public static P_GCL_LOGIN_SYN:number = 0x80029;
			//通过game广播消息
			public static P_CLG_BROADCARD_MSG:number = 0x8002a;
			//返回俱乐部申请人数
			public static P_CLC_APPLICANT_COUNT_RES:number = 0x8002b;
			//请求成功
			public static CLC_APPLICANT_COUNT_SUCCESS:number = 0x18002b;
			//经理请求俱乐部申请人数
			public static P_CCL_APPLICANT_COUNT_REQ:number = 0x8002c;
			//经理请求俱乐部申请人数
			public static P_CLC_BAN_CLUB_SYN:number = 0x8002d;
			//经理请求俱乐部申请人数
			public static P_CLC_BE_KICK_CLUB_SYN:number = 0x8002e;


			//Agent Protocols for Clients and server 0x0009xxxx, xxxx start from 0x0000
			//请求查询代理商拥有的钻石数量
			public static P_CT_HAVE_DIAMOND_REQ:number = 0x90001;
			//返回代理商的钻石数量
			public static P_TC_HAVE_DIAMOND_RES:number = 0x90002;
			//成功
			public static TC_HAVE_DIAMOND_RES_SUCCESS:number = 0x190002;
			//代理商不存在
			public static TC_HAVE_DIAMOND_RES_AGENT_NOT_EXIST:number = 0x1090002;
			//查询失败
			public static TC_HAVE_DIAMOND_RES_FAILED:number = 0x1190002;
			//无法连接GameServer,查询失败
			public static TC_HAVE_DIAMOND_RES_NOConnection:number = 0x1290002;
			//请求查询代理商钻石记录(购买或者钻石)
			public static P_CT_DIAMOND_JOURNAL_REQ:number = 0x90003;
			//返回代理商钻石记录(购买或者钻石)
			public static P_TC_DIAMOND_JOURNAL_RES:number = 0x90004;
			//成功
			public static TC_DIAMOND_JOURNAL_RES_SUCCESS:number = 0x190004;
			//代理商不存在
			public static TC_DIAMOND_JOURNAL_RES_AGENT_NOT_EXIST:number = 0x1090004;
			//查询记录失败
			public static TC_DIAMOND_JOURNAL_RES_FAILED:number = 0x1190004;
			//无法连接GameServer,查询失败
			public static TC_DIAMOND_JOURNAL_RES_NOConnection:number = 0x1290004;


			//Game Protocols for Agent and server 0x0010xxxx, xxxx start from 0x0000
			//请求代理商ID及手机号
			public static P_TG_HAVE_DIAMOND_REQ:number = 0x100001;
			//返回代理商ID及手机号
			public static P_GT_HAVE_DIAMOND_RES:number = 0x100002;
			//成功
			public static GT_HAVE_DIAMOND_RES_SUCCESS:number = 0x200002;
			//无记录，查询失败
			public static GT_HAVE_DIAMOND_RES_FAILED:number = 0x1100002;
			//请求代理商ID及手机号
			public static P_TG_DIAMOND_JOURNAL_REQ:number = 0x100003;
			//返回代理商ID及手机号
			public static P_GT_DIAMOND_JOURNAL_RES:number = 0x100004;
			//成功
			public static GT_DIAMOND_JOURNAL_RES_SUCCESS:number = 0x200004;
			//无记录，查询失败
			public static GT_DIAMOND_JOURNAL_RES_FAILED:number = 0x1100004;


			public static initMap():void{



				PlatformErrorCode.codeMap.put(PlatformErrorCode.AI_AUTH_FAILED_INVALID_CHANNEL, "微信认证失败，请重新认证");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.AI_AUTH_FAILED_INVALID_USERNAME, "微信认证失败，请重新认证");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.AI_AUTH_FAILED_INVALID_ARGUMENTS, "微信认证失败，请重新认证");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.AI_AUTH_FAILED_WX_INVALID_CODE, "微信认证失败，请重新认证");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.AI_AUTH_FAILED_WX_INVALID_REFRESH_TOKEN, "微信认证失败，请重新认证");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.AI_AUTH_FAILED_FORCE_UPDATE, "游戏版本需要更新");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.AI_AUTH_FAILED_UNKNOWN, "微信认证失败，请重新认证");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.AI_AUTH_FAILED_FORBID_REGISTER, "禁止注册");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.AI_AUTH_FAILED_INVALID_DEVICEID, "无效的设备id");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.AI_AUTH_FAILED_INVALID_APPCODE, "无效的appCode");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GI_MERGE_PLAYER_INFO_SUCCESS, "合并玩家信息成功");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GI_MERGE_PLAYER_INFO_FAIL_NO_PLAYER_INFO, "没有找到玩家信息");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.AI_VERSION_UPDATE_SUCCESS, "请求信息成功");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.AI_VERSION_UPDATE_FAIL_NO_CHANNEL_INFO, "渠道无效，登录失败");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.AI_VERSION_UPDATE_FAIL_FORCE_UPDATE, "有新版本可用，请进行更新");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.AI_VERSION_UPDATE_FAIL_MANUAL_UPDATE, "有新版本可用，是否进行更新");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.AI_VERSION_UPDATE_FAIL_REVIEW_VERSION, "");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.IC_AUTH_SUCCESS, "认证成功");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.IC_AUTH_FAILED_NO_AUTH_SERVER, "认证失败，请重新认证");


				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_LOGIN_FAILED, "登录失败，请重新登录");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_LOGIN_FAILED_INVALID_PARAM, "登录失败，请重新登录");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_LOGIN_FAILED_FORBID_ROLE, "登录失败，您已被封号");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_LOGIN_FAILED_INVALID_CHANNEL, "登录失败，渠道无效");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_LOGIN_FAILED_INVALID_PLAYER_INFO, "无效的玩家信息");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_LOGOUT_FAILED, "登录失败，请重新登录");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_CREATE_ROOM_FAILED_ROOMCARD_NOT_ENOUGTH, "钻石不足");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_CREATE_ROOM_FAILED_NO_BATTLE, "");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_CREATE_ROOM_FAILED_ALREADY_IN_ROOM, "");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_CREATE_ROOM_FAILED_CREATING, "");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_CREATE_ROOM_FAILED_INVALID_ROUND_COUNT, "");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_CREATE_ROOM_NO_LCA, "限免活动已结束");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_QUERY_BATTLEID_FAILED_ROOM_NOT_EXIST, "房间不存在");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_QUERY_BATTLEID_FAILED_CLUB_ROOM, "俱乐部房间，不能输入号码进入！");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_QUERY_BATTLEID_FAILED_CARDCOUNT_NOT_ENOUGH, "钻石不足");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_HISTORY_FAILED, "");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_HISTORY_ROOM_FAILED, "");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_HISTORY_FAILED_ROOM_HISTORY_NOT_EXIST, "房间战绩已经不存在");



				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_KICKOFF_SAME_LOGIN, "账号重复登录，您被踢下线");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_INVITER_ROOMINFO_SUCCEE, "请求信息成功");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_INVITER_ROOMINFO_FAILED_ROOM_NOT_EXIST, "请求的房间不存在");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_INVITER_ROOMINFO_FAILED_INVITER_NOT_EXIST, "邀请者不存在");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_ACTIVITY_RANK_SUCCESS, "请求信息成功");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_ACTIVITY_FAILED_NOT_EXIST, "活动不存在");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_ACTIVITY_FAILED_TOO_EARLY, "活动未开始");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_ACTIVITY_FAILED_TOO_LATE, "活动已结束");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_QUERY_TURNTABLE_INFO_SUCCESS, "查询转盘信息成功");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_TURNTABLE_DRAW_SUCCESS, "转盘抽奖成功");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_TURNTABLE_DRAW_NO_MORE_ITEM, "抽奖次数不够");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_TURNTABLE_DRAW_INACTIVE, "转盘活动未在活动期间内");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_SHARE_TURNTABLE_REWARD_SUCCESS, "");



				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_ERROR_SIGN_PN, "签名验证错误");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_AGENT_EXIST_PN, "该手机号已申请过推广员");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_AGENT_TEMP_PN, "该手机号正在申请成为推广员，请联系客服进行进一步操作");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_ERROR_PHONE_PN, "验证码发送失败，请确认手机号为有效的手机号");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_PHONE_NUMBER_PLAYER_EXIST_PN, "您已提交过申请！请勿重复申请");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_BIND_MOBILE_NO, "未绑定手机");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_BIND_MOBILE_YES, "已绑定手机");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_SEND_BIND_CODE_SUCCESS, "获取验证码成功");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_SEND_BIND_CODE_FAIL, "获取验证码失败");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_SEND_BIND_CODE_LIMIT, "获取失败，每30秒可获取一次");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_SEND_BIND_CODE_BIND_BEFORE, "已绑定，不可再次绑定");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_BIND_VAILD_OK, "已绑定，验证码正确");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_BIND_VAILD_ERROR, "验证码错误");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_BIND_VAILD_OVERTIME, "验证码过期");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_NOT_GET_CODE, "未获取验证码");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_ERROR_SIGN_VC, "签名验证错误");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_AGENT_EXIST_VC, "该手机号已申请过推广员");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_AGENT_TEMP_VC, "该手机号正在申请成为推广员，请联系客服进行进一步操作");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_ERROR_PHONE_VC, "验证码发送失败，请确认手机号为有效的手机号");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_EXRIPE_VERIYCODE_VC, "验证码发送失效");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_ERROR_VERIFYCODE_VC, "验证码错误");


				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_QUERY_PROMOTER_REWARD_FAILED_ACTIVITY_INACTIVE, "不在活动期间");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_QUERY_PROMOTER_REWARD_FAILED_PROMOTER_ABSENT, "无法查询奖励信息");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_PROMOTER_REWARD_FAILED_ACTIVITY_INACTIVE, "不在活动期间");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_PROMOTER_REWARD_FAILED, "领奖失败，未知原因");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_PROMOTER_SHARE_FAILED, "分享失败");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_POP_UP_MESSAGE_INFO_RES_VERSION_SAME, "没有新的弹窗消息");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_POP_UP_MESSAGE_INFO_RES_FAILED_MESSAGE_IS_ABSENT, "没有弹窗消息");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_CONTINUE_ROOM_FAILED_ROOMCARD_NOT_ENOUGTH, "您的钻石不足，续房失败！");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_CONTINUE_ROOM_FAILED_NO_BATTLE, "");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_CONTINUE_ROOM_FAILED_ALREADY_IN_ROOM, "");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_CONTINUE_ROOM_FAILED_CREATING, "");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_CONTINUE_ROOM_FAILED_INVALID_ROUND_COUNT, "");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_CONTINUE_ROOM_FAILED_NO_OLD_ROOM, "续房超时，无法再战");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_CONTINUE_ROOM_NO_LCA, "限免活动已结束");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_CONTINUE_ENTER_ROOM_FAILED_ROOMCARD_NOT_ENOUGTH, "您的钻石不足，续房失败！");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_CONTINUE_ENTER_ROOM_FAILED_CLUB_ROOM, "俱乐部房间，不能输入号码进入！");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_CONTINUE_ENTER_ROOM_FAILED_ROOM_NOT_EXIST, "该房间已解散，再战失败！");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_CONTINUE_ENTER_ROOM_FAILED_ROOM_FULL, "该房间人数已满，去重新创建房间吧！");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_CONTINUE_ENTER_ROOM_FAILED_NO_OLD_ROOM, "续房超时，无法再战");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_CONTINUE_ENTER_ROOM_CONNECTION_ERROR, "");


				PlatformErrorCode.codeMap.put(PlatformErrorCode.BC_ENTER_ROOM_FAILED, "");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.BC_ENTER_ROOM_FAILED_ROOM_NOT_EXIST, "房间不存在");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.BC_ENTER_ROOM_FAILED_ROOM_FULL, "房间人数已满");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.BC_ENTER_ROOM_FAILED_MEMBERS_ERROR, "");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.BC_QUIT_ROOM_FAILED, "");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.BC_QUIT_ROOM_FAILED_NOT_IN_ROOM, "");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.BC_QUIT_ROOM_FAILED_IN_BATTLE, "");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.BC_START_VOTE_FAILED_NOT_IN_ROOM, "");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.BC_START_VOTE_FAILED_WITHOUT_BATTLE, "");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.BC_START_VOTE_FAILED_VOTING, "");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.BC_VOTE_DESTROY_FAILED_NOT_IN_ROOM, "投票失败，您没有在房间中");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.BC_VOTE_DESTROY_FAILED_HAS_VOTED, "投票失败，您已经投过票");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.BC_VOTE_DESTROY_FAILED_WITHOUT_BATTLE, "投票失败，牌局还未开始");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.BC_VOTE_DESTROY_FAILED_WITHOUT_VOTE, "投票失败，没有发起投票");



				PlatformErrorCode.codeMap.put(PlatformErrorCode.BC_UPDATE_PLAYERSTATUS_FAILED_NOT_IN_ROOM, "");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.BC_UPDATE_PLAYERSTATUS_FAILED_INVALID_STATUS, "");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.BC_PLAYCARD_FAILED_NOT_IN_ROOM, "");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.BC_PLAYCARD_FAILED_NOT_HAVE_THIS_CARD, "");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.BC_PLAYCARD_FAILED_NOT_MATCH_THIS_CARD, "");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.BC_PLAYCARD_FAILED_NOT_YOUR_TURN, "");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.BC_PLAYCARD_FAILED_NOT_VALID_ROLEID, "");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.BC_CHAT_FAILED_NOT_IN_ROOM, "");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.BC_ANIMATION_FAILED_NOT_IN_ROOM, "");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.BC_GPS_INFO_FAILED_NOT_IN_ROOM, "同步失败");


				PlatformErrorCode.codeMap.put(PlatformErrorCode.BG_CREATE_ROOM_FAILED, "");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.BG_CREATE_ROOM_FAILED_ROOM_EXIST, "");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.BG_CREATE_ROOM_FAILED_INVALID_GAMEPLAYS, "");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.BG_CREATE_ROOM_FAILED_INVALID_ROUNDCOUNT, "");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.BG_INVITER_ROOMINFO_SUCCEE, "请求信息成功");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.BG_INVITER_ROOMINFO_FAILED_ROOM_NOT_EXIST, "请求的房间不存在");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.BG_INVITER_ROOMINFO_FAILED_INVITER_NOT_EXIST, "邀请者不存在");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_JOIN_ROLEINFO_SUCCEE, "请求信息成功");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_JOIN_ROLEINFO_ROLE_NOT_FOUND, "请求的玩家不存在");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.BG_CONTINUE_ROOM_FAILED, "");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.BG_CONTINUE_ROOM_FAILED_ROOM_EXIST, "");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.BG_CONTINUE_ROOM_FAILED_INVALID_GAMEPLAYS, "");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.BG_CONTINUE_ROOM_FAILED_INVALID_ROUNDCOUNT, "");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.BG_CONTINUE_ENTER_ROOM_FAILED_ROOM_NOT_EXIST, "房间不存在");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.BG_CONTINUE_ENTER_ROOM_FAILED_ROOM_FULL, "房间人数已满");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.BG_CONTINUE_ENTER_ROOM_CONNECTION_ERROR, "");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.GC_HISTORY_PLAYBACK_FAILED, "");


				PlatformErrorCode.codeMap.put(PlatformErrorCode.SS_GET_LAUNCH_INFO_FAILED, "");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.SS_PLATFORM_PURCHASE_FAILED, "");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.SS_PLATFORM_AGENT_PURCHASE_FAILED, "");


				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_CREATE_ROOM_SUCCESS, "创建成功");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_CREATE_ROOM_FAILED_NO_SUCH_CLUB, "没这个俱乐部");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_CREATE_ROOM_FAILED_NO_RIGHT, "没权限");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_CREATE_ROOM_FAILED_NOT_ENOUGH_CARDS, "俱乐部房卡不够");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_CREATE_ROOM_FAILED_MANAGER_NOT_ENOUGH_CARDS, "经理俱乐部房卡不够");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_CREATE_ROOM_FAILED_CLUB_SEALED, "俱乐部被封停");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GCL_CREATE_ROOM_SUCCESS, "创建成功");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GCL_CREATE_ROOM_FAILED_ROOM_EXIST, "");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GCL_CREATE_ROOM_FAILED_CREATING, "");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GCL_CREATE_ROOM_FAILED_ALREADY_IN_ROOM, "");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.GCL_CREATE_ROOM_FAILED_NO_BATTLE, "");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_ENTER_ROOM_SUCCESS, "创建成功");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_ENTER_ROOM_FAILED_NO_SUCH_ROOM, "没这个房间");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_ENTER_ROOM_NOT_IN_CLUB, "玩家不在这个俱乐部里");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_ENTER_ROOM_FAILED_NO_RIGHT, "没权限");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_ENTER_ROOM_FAILED_NOT_ENOUGH_CARDS, "俱乐部房卡不够");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_ENTER_ROOM_FAILED_CLUB_SEALED, "俱乐部被封停");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_CLUB_NOT_FOUND, "俱乐部不存在");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_CLUB_SEALED, "俱乐部封停");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_CLUB_WRONG_CODE, "邀请码错误");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_CLUB_KICK_OUT, "已被踢出该俱乐部");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_CLUB_JOIN_ALREADY_JOINED, "已经加入俱乐部");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_CLUB_JOIN_ALREADY_JOINED_APPLICANT, "已经在申请列表中");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_CLUB_JOIN_NOT_PERMITTED, "邀请人没有权限");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_CLUB_QUIT_NOT_IN_CLUB, "不是俱乐部成员");


				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_CLUB_NOTICEMODIFY_CLUB_NOT_FOUND, "修改失败, 俱乐部不存在");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_CLUB_NOTICEMODIFY_NOT_PERMITED, "修改失败, 没有权限");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_CLUB_NOTICEMODIFY_TEXT_TOO_LONG, "修改失败, 字数超过限制");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_CLUB_COSTMODIFY_CLUB_NOT_FOUND, "修改失败, 俱乐部不存在");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_CLUB_COSTMODIFY_NOT_PERMITED, "修改失败, 没有权限");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_CLUB_COSTMODIFY_ARGS_ERROR, "修改失败，最大可设置倍数是10");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_CLUB_MEMBERMODIFY_NOT_PERMITED, "修改失败, 没有权限");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_CLUB_APPLICANTS_CLUB_NOT_FOUND, "获取失败, 俱乐部不存在");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_CLUB_APPLICANTS_NOT_PERMITED, "获取失败, 没有权限");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_CLUB_APPLICANT_CLUB_NOT_FOUND, "失败, 俱乐部不存在");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_CLUB_APPLICANT_NOT_PERMITED, "失败, 没有权限");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_CLUB_APPLICANT_NOT_IN_LIST, "失败, 申请人不在列表中");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_CLUB_APPLICANT_MAX_CLUBS, "失败, 申请人超过了可加入俱乐部的最大限制");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_CLUB_APPLICANT_MAX_MEMBERS, "失败, 俱乐部人数限制");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_ALL_CLUB_NOT_IN_ANY_CLUB, "不在任何俱乐部中");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_CLUB_TABLE_NOT_IN_ANY_CLUB, "不在任何俱乐部中");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_CLUB_TABLE_NOT_IN_THIS_CLUB, "不在这个俱乐部中");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.CLC_CLUB_TABLE_ROOMS_NOT_FOUND, "没有任何俱乐部牌桌");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.GCL_CHECK_ROLE_INFO_ROLE_NOT_FOUND, "没有任何俱乐部牌桌");



				PlatformErrorCode.codeMap.put(PlatformErrorCode.TC_HAVE_DIAMOND_RES_AGENT_NOT_EXIST, "代理商不存在");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.TC_HAVE_DIAMOND_RES_FAILED, "查询失败");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.TC_HAVE_DIAMOND_RES_NOConnection, "无法连接GameServer,查询失败");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.TC_DIAMOND_JOURNAL_RES_AGENT_NOT_EXIST, "代理商不存在");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.TC_DIAMOND_JOURNAL_RES_FAILED, "查询记录失败");
				PlatformErrorCode.codeMap.put(PlatformErrorCode.TC_DIAMOND_JOURNAL_RES_NOConnection, "无法连接GameServer,查询失败");


				PlatformErrorCode.codeMap.put(PlatformErrorCode.GT_HAVE_DIAMOND_RES_FAILED, "无记录，查询失败");

				PlatformErrorCode.codeMap.put(PlatformErrorCode.GT_DIAMOND_JOURNAL_RES_FAILED, "无记录，查询失败");
		}
	}
}