// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/contact.proto

package com.kodgames.message.proto.contact;

public final class ContactProtoBuf {
  private ContactProtoBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CGContactREQOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.kodgames.message.proto.contact.CGContactREQ}
   */
  public static final class CGContactREQ extends
      com.google.protobuf.GeneratedMessage
      implements CGContactREQOrBuilder {
    // Use CGContactREQ.newBuilder() to construct.
    private CGContactREQ(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CGContactREQ(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CGContactREQ defaultInstance;
    public static CGContactREQ getDefaultInstance() {
      return defaultInstance;
    }

    public CGContactREQ getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CGContactREQ(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kodgames.message.proto.contact.ContactProtoBuf.internal_static_com_kodgames_message_proto_contact_CGContactREQ_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kodgames.message.proto.contact.ContactProtoBuf.internal_static_com_kodgames_message_proto_contact_CGContactREQ_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kodgames.message.proto.contact.ContactProtoBuf.CGContactREQ.class, com.kodgames.message.proto.contact.ContactProtoBuf.CGContactREQ.Builder.class);
    }

    public static com.google.protobuf.Parser<CGContactREQ> PARSER =
        new com.google.protobuf.AbstractParser<CGContactREQ>() {
      public CGContactREQ parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CGContactREQ(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CGContactREQ> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.kodgames.message.proto.contact.ContactProtoBuf.CGContactREQ parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kodgames.message.proto.contact.ContactProtoBuf.CGContactREQ parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kodgames.message.proto.contact.ContactProtoBuf.CGContactREQ parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kodgames.message.proto.contact.ContactProtoBuf.CGContactREQ parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kodgames.message.proto.contact.ContactProtoBuf.CGContactREQ parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kodgames.message.proto.contact.ContactProtoBuf.CGContactREQ parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.kodgames.message.proto.contact.ContactProtoBuf.CGContactREQ parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.kodgames.message.proto.contact.ContactProtoBuf.CGContactREQ parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.kodgames.message.proto.contact.ContactProtoBuf.CGContactREQ parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kodgames.message.proto.contact.ContactProtoBuf.CGContactREQ parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.kodgames.message.proto.contact.ContactProtoBuf.CGContactREQ prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.kodgames.message.proto.contact.CGContactREQ}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.kodgames.message.proto.contact.ContactProtoBuf.CGContactREQOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kodgames.message.proto.contact.ContactProtoBuf.internal_static_com_kodgames_message_proto_contact_CGContactREQ_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kodgames.message.proto.contact.ContactProtoBuf.internal_static_com_kodgames_message_proto_contact_CGContactREQ_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kodgames.message.proto.contact.ContactProtoBuf.CGContactREQ.class, com.kodgames.message.proto.contact.ContactProtoBuf.CGContactREQ.Builder.class);
      }

      // Construct using com.kodgames.message.proto.contact.ContactProtoBuf.CGContactREQ.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kodgames.message.proto.contact.ContactProtoBuf.internal_static_com_kodgames_message_proto_contact_CGContactREQ_descriptor;
      }

      public com.kodgames.message.proto.contact.ContactProtoBuf.CGContactREQ getDefaultInstanceForType() {
        return com.kodgames.message.proto.contact.ContactProtoBuf.CGContactREQ.getDefaultInstance();
      }

      public com.kodgames.message.proto.contact.ContactProtoBuf.CGContactREQ build() {
        com.kodgames.message.proto.contact.ContactProtoBuf.CGContactREQ result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kodgames.message.proto.contact.ContactProtoBuf.CGContactREQ buildPartial() {
        com.kodgames.message.proto.contact.ContactProtoBuf.CGContactREQ result = new com.kodgames.message.proto.contact.ContactProtoBuf.CGContactREQ(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kodgames.message.proto.contact.ContactProtoBuf.CGContactREQ) {
          return mergeFrom((com.kodgames.message.proto.contact.ContactProtoBuf.CGContactREQ)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kodgames.message.proto.contact.ContactProtoBuf.CGContactREQ other) {
        if (other == com.kodgames.message.proto.contact.ContactProtoBuf.CGContactREQ.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kodgames.message.proto.contact.ContactProtoBuf.CGContactREQ parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kodgames.message.proto.contact.ContactProtoBuf.CGContactREQ) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.kodgames.message.proto.contact.CGContactREQ)
    }

    static {
      defaultInstance = new CGContactREQ(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.kodgames.message.proto.contact.CGContactREQ)
  }

  public interface GCContactRESOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 result = 1;
    /**
     * <code>required int32 result = 1;</code>
     *
     * <pre>
     * 请求结果
     * </pre>
     */
    boolean hasResult();
    /**
     * <code>required int32 result = 1;</code>
     *
     * <pre>
     * 请求结果
     * </pre>
     */
    int getResult();

    // optional string content = 2;
    /**
     * <code>optional string content = 2;</code>
     *
     * <pre>
     * 代理商信息
     * </pre>
     */
    boolean hasContent();
    /**
     * <code>optional string content = 2;</code>
     *
     * <pre>
     * 代理商信息
     * </pre>
     */
    java.lang.String getContent();
    /**
     * <code>optional string content = 2;</code>
     *
     * <pre>
     * 代理商信息
     * </pre>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    // repeated string weiXins = 3;
    /**
     * <code>repeated string weiXins = 3;</code>
     *
     * <pre>
     * 客服微信号
     * </pre>
     */
    java.util.List<java.lang.String>
    getWeiXinsList();
    /**
     * <code>repeated string weiXins = 3;</code>
     *
     * <pre>
     * 客服微信号
     * </pre>
     */
    int getWeiXinsCount();
    /**
     * <code>repeated string weiXins = 3;</code>
     *
     * <pre>
     * 客服微信号
     * </pre>
     */
    java.lang.String getWeiXins(int index);
    /**
     * <code>repeated string weiXins = 3;</code>
     *
     * <pre>
     * 客服微信号
     * </pre>
     */
    com.google.protobuf.ByteString
        getWeiXinsBytes(int index);
  }
  /**
   * Protobuf type {@code com.kodgames.message.proto.contact.GCContactRES}
   */
  public static final class GCContactRES extends
      com.google.protobuf.GeneratedMessage
      implements GCContactRESOrBuilder {
    // Use GCContactRES.newBuilder() to construct.
    private GCContactRES(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GCContactRES(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GCContactRES defaultInstance;
    public static GCContactRES getDefaultInstance() {
      return defaultInstance;
    }

    public GCContactRES getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GCContactRES(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              content_ = input.readBytes();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                weiXins_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              weiXins_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          weiXins_ = new com.google.protobuf.UnmodifiableLazyStringList(weiXins_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kodgames.message.proto.contact.ContactProtoBuf.internal_static_com_kodgames_message_proto_contact_GCContactRES_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kodgames.message.proto.contact.ContactProtoBuf.internal_static_com_kodgames_message_proto_contact_GCContactRES_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kodgames.message.proto.contact.ContactProtoBuf.GCContactRES.class, com.kodgames.message.proto.contact.ContactProtoBuf.GCContactRES.Builder.class);
    }

    public static com.google.protobuf.Parser<GCContactRES> PARSER =
        new com.google.protobuf.AbstractParser<GCContactRES>() {
      public GCContactRES parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GCContactRES(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GCContactRES> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>required int32 result = 1;</code>
     *
     * <pre>
     * 请求结果
     * </pre>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 result = 1;</code>
     *
     * <pre>
     * 请求结果
     * </pre>
     */
    public int getResult() {
      return result_;
    }

    // optional string content = 2;
    public static final int CONTENT_FIELD_NUMBER = 2;
    private java.lang.Object content_;
    /**
     * <code>optional string content = 2;</code>
     *
     * <pre>
     * 代理商信息
     * </pre>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string content = 2;</code>
     *
     * <pre>
     * 代理商信息
     * </pre>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string content = 2;</code>
     *
     * <pre>
     * 代理商信息
     * </pre>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string weiXins = 3;
    public static final int WEIXINS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList weiXins_;
    /**
     * <code>repeated string weiXins = 3;</code>
     *
     * <pre>
     * 客服微信号
     * </pre>
     */
    public java.util.List<java.lang.String>
        getWeiXinsList() {
      return weiXins_;
    }
    /**
     * <code>repeated string weiXins = 3;</code>
     *
     * <pre>
     * 客服微信号
     * </pre>
     */
    public int getWeiXinsCount() {
      return weiXins_.size();
    }
    /**
     * <code>repeated string weiXins = 3;</code>
     *
     * <pre>
     * 客服微信号
     * </pre>
     */
    public java.lang.String getWeiXins(int index) {
      return weiXins_.get(index);
    }
    /**
     * <code>repeated string weiXins = 3;</code>
     *
     * <pre>
     * 客服微信号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getWeiXinsBytes(int index) {
      return weiXins_.getByteString(index);
    }

    private void initFields() {
      result_ = 0;
      content_ = "";
      weiXins_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getContentBytes());
      }
      for (int i = 0; i < weiXins_.size(); i++) {
        output.writeBytes(3, weiXins_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getContentBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < weiXins_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(weiXins_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getWeiXinsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.kodgames.message.proto.contact.ContactProtoBuf.GCContactRES parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kodgames.message.proto.contact.ContactProtoBuf.GCContactRES parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kodgames.message.proto.contact.ContactProtoBuf.GCContactRES parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kodgames.message.proto.contact.ContactProtoBuf.GCContactRES parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kodgames.message.proto.contact.ContactProtoBuf.GCContactRES parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kodgames.message.proto.contact.ContactProtoBuf.GCContactRES parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.kodgames.message.proto.contact.ContactProtoBuf.GCContactRES parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.kodgames.message.proto.contact.ContactProtoBuf.GCContactRES parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.kodgames.message.proto.contact.ContactProtoBuf.GCContactRES parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kodgames.message.proto.contact.ContactProtoBuf.GCContactRES parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.kodgames.message.proto.contact.ContactProtoBuf.GCContactRES prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.kodgames.message.proto.contact.GCContactRES}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.kodgames.message.proto.contact.ContactProtoBuf.GCContactRESOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kodgames.message.proto.contact.ContactProtoBuf.internal_static_com_kodgames_message_proto_contact_GCContactRES_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kodgames.message.proto.contact.ContactProtoBuf.internal_static_com_kodgames_message_proto_contact_GCContactRES_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kodgames.message.proto.contact.ContactProtoBuf.GCContactRES.class, com.kodgames.message.proto.contact.ContactProtoBuf.GCContactRES.Builder.class);
      }

      // Construct using com.kodgames.message.proto.contact.ContactProtoBuf.GCContactRES.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        weiXins_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kodgames.message.proto.contact.ContactProtoBuf.internal_static_com_kodgames_message_proto_contact_GCContactRES_descriptor;
      }

      public com.kodgames.message.proto.contact.ContactProtoBuf.GCContactRES getDefaultInstanceForType() {
        return com.kodgames.message.proto.contact.ContactProtoBuf.GCContactRES.getDefaultInstance();
      }

      public com.kodgames.message.proto.contact.ContactProtoBuf.GCContactRES build() {
        com.kodgames.message.proto.contact.ContactProtoBuf.GCContactRES result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kodgames.message.proto.contact.ContactProtoBuf.GCContactRES buildPartial() {
        com.kodgames.message.proto.contact.ContactProtoBuf.GCContactRES result = new com.kodgames.message.proto.contact.ContactProtoBuf.GCContactRES(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.content_ = content_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          weiXins_ = new com.google.protobuf.UnmodifiableLazyStringList(
              weiXins_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.weiXins_ = weiXins_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kodgames.message.proto.contact.ContactProtoBuf.GCContactRES) {
          return mergeFrom((com.kodgames.message.proto.contact.ContactProtoBuf.GCContactRES)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kodgames.message.proto.contact.ContactProtoBuf.GCContactRES other) {
        if (other == com.kodgames.message.proto.contact.ContactProtoBuf.GCContactRES.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000002;
          content_ = other.content_;
          onChanged();
        }
        if (!other.weiXins_.isEmpty()) {
          if (weiXins_.isEmpty()) {
            weiXins_ = other.weiXins_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureWeiXinsIsMutable();
            weiXins_.addAll(other.weiXins_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kodgames.message.proto.contact.ContactProtoBuf.GCContactRES parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kodgames.message.proto.contact.ContactProtoBuf.GCContactRES) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 result = 1;
      private int result_ ;
      /**
       * <code>required int32 result = 1;</code>
       *
       * <pre>
       * 请求结果
       * </pre>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 result = 1;</code>
       *
       * <pre>
       * 请求结果
       * </pre>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>required int32 result = 1;</code>
       *
       * <pre>
       * 请求结果
       * </pre>
       */
      public Builder setResult(int value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 result = 1;</code>
       *
       * <pre>
       * 请求结果
       * </pre>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }

      // optional string content = 2;
      private java.lang.Object content_ = "";
      /**
       * <code>optional string content = 2;</code>
       *
       * <pre>
       * 代理商信息
       * </pre>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string content = 2;</code>
       *
       * <pre>
       * 代理商信息
       * </pre>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string content = 2;</code>
       *
       * <pre>
       * 代理商信息
       * </pre>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string content = 2;</code>
       *
       * <pre>
       * 代理商信息
       * </pre>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 2;</code>
       *
       * <pre>
       * 代理商信息
       * </pre>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 2;</code>
       *
       * <pre>
       * 代理商信息
       * </pre>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
        return this;
      }

      // repeated string weiXins = 3;
      private com.google.protobuf.LazyStringList weiXins_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureWeiXinsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          weiXins_ = new com.google.protobuf.LazyStringArrayList(weiXins_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string weiXins = 3;</code>
       *
       * <pre>
       * 客服微信号
       * </pre>
       */
      public java.util.List<java.lang.String>
          getWeiXinsList() {
        return java.util.Collections.unmodifiableList(weiXins_);
      }
      /**
       * <code>repeated string weiXins = 3;</code>
       *
       * <pre>
       * 客服微信号
       * </pre>
       */
      public int getWeiXinsCount() {
        return weiXins_.size();
      }
      /**
       * <code>repeated string weiXins = 3;</code>
       *
       * <pre>
       * 客服微信号
       * </pre>
       */
      public java.lang.String getWeiXins(int index) {
        return weiXins_.get(index);
      }
      /**
       * <code>repeated string weiXins = 3;</code>
       *
       * <pre>
       * 客服微信号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getWeiXinsBytes(int index) {
        return weiXins_.getByteString(index);
      }
      /**
       * <code>repeated string weiXins = 3;</code>
       *
       * <pre>
       * 客服微信号
       * </pre>
       */
      public Builder setWeiXins(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureWeiXinsIsMutable();
        weiXins_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string weiXins = 3;</code>
       *
       * <pre>
       * 客服微信号
       * </pre>
       */
      public Builder addWeiXins(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureWeiXinsIsMutable();
        weiXins_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string weiXins = 3;</code>
       *
       * <pre>
       * 客服微信号
       * </pre>
       */
      public Builder addAllWeiXins(
          java.lang.Iterable<java.lang.String> values) {
        ensureWeiXinsIsMutable();
        super.addAll(values, weiXins_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string weiXins = 3;</code>
       *
       * <pre>
       * 客服微信号
       * </pre>
       */
      public Builder clearWeiXins() {
        weiXins_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string weiXins = 3;</code>
       *
       * <pre>
       * 客服微信号
       * </pre>
       */
      public Builder addWeiXinsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureWeiXinsIsMutable();
        weiXins_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.kodgames.message.proto.contact.GCContactRES)
    }

    static {
      defaultInstance = new GCContactRES(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.kodgames.message.proto.contact.GCContactRES)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kodgames_message_proto_contact_CGContactREQ_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_kodgames_message_proto_contact_CGContactREQ_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kodgames_message_proto_contact_GCContactRES_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_kodgames_message_proto_contact_GCContactRES_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026protobuf/contact.proto\022\"com.kodgames.m" +
      "essage.proto.contact\"\016\n\014CGContactREQ\"@\n\014" +
      "GCContactRES\022\016\n\006result\030\001 \002(\005\022\017\n\007content\030" +
      "\002 \001(\t\022\017\n\007weiXins\030\003 \003(\tB\021B\017ContactProtoBu" +
      "f"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_kodgames_message_proto_contact_CGContactREQ_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_kodgames_message_proto_contact_CGContactREQ_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_kodgames_message_proto_contact_CGContactREQ_descriptor,
              new java.lang.String[] { });
          internal_static_com_kodgames_message_proto_contact_GCContactRES_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_kodgames_message_proto_contact_GCContactRES_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_kodgames_message_proto_contact_GCContactRES_descriptor,
              new java.lang.String[] { "Result", "Content", "WeiXins", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
